/**
 * @file canbus_msg.h
 * @brief Autogenerated CAN definitions - Generated on 2026-02-06 00:51:27
 * @note DO NOT EDIT MANUALLY
 */
#ifndef CANBUS_MSG_H_
#define CANBUS_MSG_H_

#include <stdint.h>

/* ========================================================================== */
/* --- 16-BIT FEATURE MASKS ---                                               */
/* ========================================================================== */
#define FEATURE_BOX_SW_6GANG_HIGH                                         ((uint16_t)0x8EC0) /** feature mask for 6-gang switch box, 4 high, 2 low */
#define FEATURE_BOX_SW_3GANG                                              ((uint16_t)0x8E60) /** feature mask for 3-gang output, 2 high, 1 low */
#define FEATURE_BOX_SW_2GANG_LOW                                          ((uint16_t)0x8E40) /** feature mask for 2-gang switch box, 2 low */
#define FEATURE_BOX_SW_4GANG                                              ((uint16_t)0x8E80) /** feature mask for 4-gang switch box, 2 high, 2 low */
#define FEATURE_BOX_SW_4RELAY                                             ((uint16_t)0x8C08) /** feature mask for 4-gang relay output box */
#define FEATURE_BOX_SW_6GANG_LOW                                          ((uint16_t)0x8EC0) /** feature mask for 6-gang switch box, 2 high, 4 low */
#define FEATURE_BOX_SW_2GANG_HIGH                                         ((uint16_t)0x8E40) /** feature mask for 2-gang switch box, 2 high */
#define FEATURE_BOX_SW_8RELAY                                             ((uint16_t)0x8C10) /** feature mask for 8-gang relay output box */
#define FEATURE_BOX_MULTI_4X4IO                                           ((uint16_t)0xCC08) /** feature mask for input - output box, 4 in, 4 out */
#define FEATURE_BOX_MULTI_4XTEMP                                          ((uint16_t)0xCC00) /** feature mask for 4-digital multi temp input box */
#define FEATURE_BOX_MULTI_TVA                                             ((uint16_t)0xBC00) /** feature mask for temp, volt, current input box */
#define FEATURE_IFACE_8X4_ARGB                                            ((uint16_t)0xC1A4) /** feature mask for 8x4 argb keypad */
#define FEATURE_IFACE_4X4_ARGB                                            ((uint16_t)0xA1A4) /** feature mask for 4x4 argb keypad */
#define FEATURE_IFACE_TOUCHSCREEN_TYPE_A                                  ((uint16_t)0x81D8) /** feature mask for touchscreen type a */
#define FEATURE_IFACE_TOUCHSCREEN_TYPE_B                                  ((uint16_t)0x81D8) /** feature mask for touchscreen type b */
#define FEATURE_IFACE_NEXTION_TYPE_A                                      ((uint16_t)0x81D8) /** feature mask for nextion type a */
#define FEATURE_IFACE_NEXTION_TYPE_B                                      ((uint16_t)0x81D8) /** feature mask for nextion type b */
#define FEATURE_IFACE_6_AXIS_IMU                                          ((uint16_t)0x9180) /** feature mask for 6-axis IMU */
#define FEATURE_IFACE_3X5_BUTTON_BOX                                      ((uint16_t)0x9F80) /** feature mask for 3x5 button box */
#define FEATURE_IFACE_4x6_BUTTON_BOX                                      ((uint16_t)0xB180) /** feature mask for 4x6 button box */
#define FEATURE_DISP_ANALOG_LED_STRIP                                     ((uint16_t)0x81E2) /** feature mask for analog led strip */
#define FEATURE_DISP_ARGBW_LED_STRIP                                      ((uint16_t)0x81E4) /** feature mask for argbw led strip */
#define FEATURE_DISP_ARGB_LED_STRIP                                       ((uint16_t)0x8064) /** feature mask for argb led strip */
#define FEATURE_DISP_OLED                                                 ((uint16_t)0x8040) /** feature mask for non-touch oled display */
#define FEATURE_DISP_LCD                                                  ((uint16_t)0x8048) /** feature mask for non-touch lcd display */
#define FEATURE_INPUT_DIGITAL_TEMP                                        ((uint16_t)0x0000) /** feature mask for input digital temp */
#define FEATURE_INPUT_K_TYPE_TEMP                                         ((uint16_t)0x0008) /** feature mask for input k type temp */
#define FEATURE_NODE_LASTBOOT                                             ((uint16_t)0x0004) /** feature mask for last boot timestamp */
#define FEATURE_NODE_PCB_TEMP                                             ((uint16_t)0x0011) /** feature mask for node pcb temp */
#define FEATURE_NODE_CPU_TEMP                                             ((uint16_t)0x0020) /** feature mask for node cpu temp */
#define FEATURE_INPUT_EXT_VOLTAGE_SENSOR                                  ((uint16_t)0x0040) /** feature mask for input ext voltage sensor */
#define FEATURE_NODE_INT_VOLTAGE_SENSOR                                   ((uint16_t)0x0042) /** feature mask for node int voltage sensor */
#define FEATURE_NODE_INT_CURRENT_SENSOR                                   ((uint16_t)0x0000) /** feature mask for node int current sensor */
#define FEATURE_INPUT_EXT_CURRENT_SHUNT                                   ((uint16_t)0x0000) /** feature mask for input ext current shunt */
#define FEATURE_INPUT_EXT_CURRENT_HALL                                    ((uint16_t)0x0010) /** feature mask for input ext current hall */
#define FEATURE_SENSOR_RESERVED_72A                                       ((uint16_t)0x0044) /** feature mask for sensor reserved 72a */
#define FEATURE_SENSOR_RESERVED_72B                                       ((uint16_t)0x0000) /** feature mask for sensor reserved 72b */
#define FEATURE_GPS_ALTITUDE                                              ((uint16_t)0x0000) /** feature mask for GPS altitude */
#define FEATURE_GPS_STATUS                                                ((uint16_t)0x0000) /** feature mask for GPS status */
#define FEATURE_SENSOR_RESERVED_72E                                       ((uint16_t)0x0040) /** feature mask for sensor reserved 72e */
#define FEATURE_SENSOR_RESERVED_72F                                       ((uint16_t)0x0020) /** feature mask for sensor reserved 72f */
#define FEATURE_IMU_X_AXIS_SENSOR                                         ((uint16_t)0x0000) /** feature mask for IMU X Axis sensor */
#define FEATURE_IMU_Y_AXIS_SENSOR                                         ((uint16_t)0x0011) /** feature mask for IMU Y Axis sensor */
#define FEATURE_IMU_Z_AXIS_SENSOR                                         ((uint16_t)0x0010) /** feature mask for IMU Z Axis sensor */
#define FEATURE_IMU_X_GYRO_SENSOR                                         ((uint16_t)0x0008) /** feature mask for IMU X Gyro sensor */
#define FEATURE_IMU_Y_GYRO_SENSOR                                         ((uint16_t)0x0044) /** feature mask for IMU Y Gyro sensor */
#define FEATURE_GPS_UTC_TIME                                              ((uint16_t)0x0001) /** feature mask for GPS utc time */
#define FEATURE_GPS_LATITUDE                                              ((uint16_t)0x0002) /** feature mask for GPS latitude */
#define FEATURE_GPS_NS_IND                                                ((uint16_t)0x0002) /** feature mask for GPS NS IND */
#define FEATURE_OUT_LOW_CURRENT_SW                                        ((uint16_t)0x0400) /** feature mask for low current solid state switch */
#define FEATURE_OUT_OPEN_DRAIN                                            ((uint16_t)0x0200) /** feature mask for open drain output */
#define FEATURE_OUT_MECH_RELAY                                            ((uint16_t)0x0200) /** feature mask for mechanical relay */
#define FEATURE_OUT_RESERVED_744                                          ((uint16_t)0x0200) /** feature mask for out reserved 744 */
#define FEATURE_OUT_RESERVED_745                                          ((uint16_t)0x0200) /** feature mask for out reserved 745 */
#define FEATURE_OUT_RESERVED_746                                          ((uint16_t)0x0200) /** feature mask for out reserved 746 */
#define FEATURE_OUT_RESERVED_747                                          ((uint16_t)0x0200) /** feature mask for out reserved 747 */
#define FEATURE_OUT_RESERVED_74B                                          ((uint16_t)0x0100) /** feature mask for out reserved 74b */
#define FEATURE_OUT_RESERVED_74C                                          ((uint16_t)0x0100) /** feature mask for out reserved 74c */
#define FEATURE_OUT_RESERVED_74D                                          ((uint16_t)0x0100) /** feature mask for out reserved 74d */
#define FEATURE_OUT_RESERVED_74E                                          ((uint16_t)0x0100) /** feature mask for out reserved 74e */
#define FEATURE_OUT_RESERVED_74F                                          ((uint16_t)0x0100) /** feature mask for out reserved 74f */
#define FEATURE_GPS_LONGITUDE                                             ((uint16_t)0x0100) /** feature mask for GPS longitude */
#define FEATURE_GPS_EW_IND                                                ((uint16_t)0x0100) /** feature mask for GPS EW IND */

/* ========================================================================== */
/* --- CAN MESSAGE IDS AND DLCS ---                                           */
/* ========================================================================== */
#define CAN_ID_ERROR_OVER_CURRENT                                         (0x100) /** error condition over current */
#define CAN_DLC_ERROR_OVER_CURRENT                                        (6)

#define CAN_ID_ERROR_OVER_TEMP                                            (0x101) /** error condition over temp */
#define CAN_DLC_ERROR_OVER_TEMP                                           (6)

#define CAN_ID_ERROR_OVER_VOLT                                            (0x102) /** error condition over volt */
#define CAN_DLC_ERROR_OVER_VOLT                                           (6)

#define CAN_ID_SW_RESERVED110                                             (0x110) /** reserved 110 */

#define CAN_ID_SW_RESERVED111                                             (0x111) /** reserved 111 */

#define CAN_ID_SW_SET_MODE                                                (0x112) /** set switch mode */
#define CAN_DLC_SW_SET_MODE                                               (6)

#define CAN_ID_SW_SET_OFF                                                 (0x113) /** switch off */
#define CAN_DLC_SW_SET_OFF                                                (5)

#define CAN_ID_SW_SET_ON                                                  (0x114) /** switch on */
#define CAN_DLC_SW_SET_ON                                                 (5)

#define CAN_ID_SW_MOM_PRESS                                               (0x115) /** switch momentary press */
#define CAN_DLC_SW_MOM_PRESS                                              (5)

#define CAN_ID_SW_SET_MOM_DUR                                             (0x116) /** set momentary switch duration ms */
#define CAN_DLC_SW_SET_MOM_DUR                                            (7)

#define CAN_ID_SW_SET_PWM_DUTY                                            (0x117) /** switch set pwm duty */
#define CAN_DLC_SW_SET_PWM_DUTY                                           (7)

#define CAN_ID_SW_SET_PWM_FREQ                                            (0x118) /** switch set pwm freq */
#define CAN_DLC_SW_SET_PWM_FREQ                                           (7)

#define CAN_ID_SW_SET_BLINK_DELAY                                         (0x119) /** switch set blink delay in tenths of a second 1-100 */
#define CAN_DLC_SW_SET_BLINK_DELAY                                        (7)

#define CAN_ID_SW_SET_STROBE_PAT                                          (0x11A) /** switch set strobe pattern */
#define CAN_DLC_SW_SET_STROBE_PAT                                         (6)

#define CAN_ID_SW_SET_STATE_MEM                                           (0x11B) /** enable / disable switch last state memory */
#define CAN_DLC_SW_SET_STATE_MEM                                          (6)

#define CAN_ID_SET_DISPLAY_OFF                                            (0x200) /** set display off */
#define CAN_DLC_SET_DISPLAY_OFF                                           (5)

#define CAN_ID_SET_DISPLAY_ON                                             (0x201) /** set display on */
#define CAN_DLC_SET_DISPLAY_ON                                            (5)

#define CAN_ID_SET_DISPLAY_CLEAR                                          (0x202) /** set display clear */
#define CAN_DLC_SET_DISPLAY_CLEAR                                         (5)

#define CAN_ID_SET_DISPLAY_FLASH                                          (0x203) /** set display flash */
#define CAN_DLC_SET_DISPLAY_FLASH                                         (6)

#define CAN_ID_SET_DISPLAY_BACKLIGHT_COLOR                                (0x204) /** set display backlight color */
#define CAN_DLC_SET_DISPLAY_BACKLIGHT_COLOR                               (7)

#define CAN_ID_SET_DISPLAY_BACKLIGHT_BRIGHTNESS                           (0x205) /** set display backlight brightness */
#define CAN_DLC_SET_DISPLAY_BACKLIGHT_BRIGHTNESS                          (6)

#define CAN_ID_REQ_DISPLAY_CONFIG                                         (0x206) /** req display config */
#define CAN_DLC_REQ_DISPLAY_CONFIG                                        (6)

#define CAN_ID_REQ_DISPLAY_DATA                                           (0x207) /** req display data */
#define CAN_DLC_REQ_DISPLAY_DATA                                          (6)

#define CAN_ID_SET_OLED_FIELD_COLOR                                       (0x208) /** set oled field color */
#define CAN_DLC_SET_OLED_FIELD_COLOR                                      (8)

#define CAN_ID_SET_OLED_FIELD_BLINK                                       (0x209) /** set oled field blink */
#define CAN_DLC_SET_OLED_FIELD_BLINK                                      (8)

#define CAN_ID_SET_OLED_FIELD_STROBE                                      (0x20A) /** set oled field strobe */
#define CAN_DLC_SET_OLED_FIELD_STROBE                                     (8)

#define CAN_ID_SET_DISPLAY_RESERVED_20B                                   (0x20B) /** set display reserved 20b */
#define CAN_DLC_SET_DISPLAY_RESERVED_20B                                  (8)

#define CAN_ID_SET_DISPLAY_RESERVED_20C                                   (0x20C) /** set display reserved 20c */
#define CAN_DLC_SET_DISPLAY_RESERVED_20C                                  (8)

#define CAN_ID_DISPLAY_DATA_MSG                                           (0x20D) /** display data msg */
#define CAN_DLC_DISPLAY_DATA_MSG                                          (8)

#define CAN_ID_DISPLAY_DATA_ACK                                           (0x20E) /** display data ack */
#define CAN_DLC_DISPLAY_DATA_ACK                                          (8)

#define CAN_ID_SET_DISPLAY_RESERVED_20F                                   (0x20F) /** set display reserved 20f */
#define CAN_DLC_SET_DISPLAY_RESERVED_20F                                  (0)

#define CAN_ID_SET_ARGB_STRIP_COLOR                                       (0x210) /** set argb strip color */
#define CAN_DLC_SET_ARGB_STRIP_COLOR                                      (0)

#define CAN_ID_SET_ARGBW_STRIP_COLOR                                      (0x211) /** set argbw strip color */
#define CAN_DLC_SET_ARGBW_STRIP_COLOR                                     (7)

#define CAN_ID_SET_ANALOG_STRIP_COLOR                                     (0x212) /** set analog strip color */
#define CAN_DLC_SET_ANALOG_STRIP_COLOR                                    (7)

#define CAN_ID_SET_ADDR_STRIP_EFFECT                                      (0x213) /** set addr strip effect */
#define CAN_DLC_SET_ADDR_STRIP_EFFECT                                     (7)

#define CAN_ID_SET_LED_STRIP_BRIGHTNESS                                   (0x214) /** set led strip brightness */
#define CAN_DLC_SET_LED_STRIP_BRIGHTNESS                                  (7)

#define CAN_ID_SET_LED_STRIP_OFF                                          (0x215) /** set led strip off */
#define CAN_DLC_SET_LED_STRIP_OFF                                         (7)

#define CAN_ID_SET_LED_STRIP_ON                                           (0x216) /** set led strip on */
#define CAN_DLC_SET_LED_STRIP_ON                                          (5)

#define CAN_ID_SET_LED_RESERVED_217                                       (0x217) /** set led reserved 217 */
#define CAN_DLC_SET_LED_RESERVED_217                                      (5)

#define CAN_ID_SET_LED_RESERVED_218                                       (0x218) /** set led reserved 218 */

#define CAN_ID_SET_LED_RESERVED_219                                       (0x219) /** set led reserved 219 */

#define CAN_ID_SET_LED_RESERVED_21A                                       (0x21A) /** set led reserved 21a */

#define CAN_ID_SET_LED_RESERVED_21B                                       (0x21B) /** set led reserved 21b */

#define CAN_ID_SET_LED_RESERVED_21C                                       (0x21C) /** set led reserved 21c */

#define CAN_ID_SET_LED_RESERVED_21D                                       (0x21D) /** set led reserved 21d */

#define CAN_ID_SET_LED_RESERVED_21E                                       (0x21E) /** set led reserved 21e */

#define CAN_ID_SET_LED_RESERVED_21F                                       (0x21F) /** set led reserved 21f */

#define CAN_ID_SET_ARGB_BUTTON_COLOR                                      (0x220) /** set argb button color */

#define CAN_ID_SET_ARGB_BUTTON_LED_MODE                                   (0x221) /** set argb button led mode */

#define CAN_ID_SET_BUTTON_MODE                                            (0x222) /** set button mode 0 disabled, 1 toggle, 2 momentary */

#define CAN_ID_ACK_INTRO                                                  (0x400) /** acknowledge introduction, clear flag on remote device */
#define CAN_DLC_ACK_INTRO                                                 (4)

#define CAN_ID_REQ_NODE_INTRO                                             (0x401) /** general intro request for all node types */
#define CAN_DLC_REQ_NODE_INTRO                                            (4)

#define CAN_ID_MSG_NORM_OPER                                              (0x402) /** message to all nodes to being normal operation, sent after introduction and enumeration are complete */
#define CAN_DLC_MSG_NORM_OPER                                             (4)

#define CAN_ID_MSG_HALT_OPER                                              (0x403) /** message to all nodes to stop transmitting messages and wait for instructions */
#define CAN_DLC_MSG_HALT_OPER                                             (4)

#define CAN_ID_REQ_NODECHECK                                              (0x404) /** remote nodes should respond with their node id and last boot timestamp */
#define CAN_DLC_REQ_NODECHECK                                             (4)

#define CAN_ID_REQ_HEALTHCHECK                                            (0x405) /** remote nodes should respond with diagnostic sensor data */
#define CAN_DLC_REQ_HEALTHCHECK                                           (4)

#define CAN_ID_REQ_IFACE                                                  (0x406) /** req interfaces node include buttons, displays leds and sensors */
#define CAN_DLC_REQ_IFACE                                                 (4)

#define CAN_ID_REQ_SWITCHBOX                                              (0x407) /** req switch boxes nodes include anything that controls a load */
#define CAN_DLC_REQ_SWITCHBOX                                             (4)

#define CAN_ID_DATA_EPOCH                                                 (0x40C) /** epoch timestamp from controller */
#define CAN_DLC_DATA_EPOCH                                                (8)

#define CAN_ID_DATA_SENSOR_MSG                                            (0x40D) /** controller assigned message id to use for transferring sensor data range 72A:72F */
#define CAN_DLC_DATA_SENSOR_MSG                                           (8)

#define CAN_ID_REQ_BUTTONS                                                (0x410) /** req buttons */
#define CAN_DLC_REQ_BUTTONS                                               (4)

#define CAN_ID_REQ_OUTPUTS                                                (0x411) /** req outputs */
#define CAN_DLC_REQ_OUTPUTS                                               (4)

#define CAN_ID_REQ_DISPLAYS                                               (0x412) /** req displays */
#define CAN_DLC_REQ_DISPLAYS                                              (4)

#define CAN_ID_REQ_TEMP_SENSOR                                            (0x413) /** req temp sensor */
#define CAN_DLC_REQ_TEMP_SENSOR                                           (4)

#define CAN_ID_REQ_VOLT_SENSOR                                            (0x414) /** req volt sensor */
#define CAN_DLC_REQ_VOLT_SENSOR                                           (4)

#define CAN_ID_REQ_AMP_SENSOR                                             (0x415) /** req amp sensor */
#define CAN_DLC_REQ_AMP_SENSOR                                            (4)

#define CAN_ID_REQ_CLOSURE_INPUT                                          (0x416) /** req closure input */
#define CAN_DLC_REQ_CLOSURE_INPUT                                         (4)

#define CAN_ID_REQ_AMBIENT_LIGHT                                          (0x417) /** req ambient light sensors */
#define CAN_DLC_REQ_AMBIENT_LIGHT                                         (4)

#define CAN_ID_REQ_IMU_SENSORS                                            (0x418) /** req imu sensors */
#define CAN_DLC_REQ_IMU_SENSORS                                           (4)

#define CAN_ID_DATA_BUTTON_DOWN                                           (0x500) /** button down */
#define CAN_DLC_DATA_BUTTON_DOWN                                          (7)

#define CAN_ID_DATA_BUTTON_UP                                             (0x501) /** button up */
#define CAN_DLC_DATA_BUTTON_UP                                            (7)

#define CAN_ID_DATA_KEYSWITCH_LOCK                                        (0x502) /** keyswitch lock */
#define CAN_DLC_DATA_KEYSWITCH_LOCK                                       (7)

#define CAN_ID_DATA_KEYSWITCH_UNLOCK                                      (0x503) /** keyswitch unlock */
#define CAN_DLC_DATA_KEYSWITCH_UNLOCK                                     (7)

#define CAN_ID_DATA_DIAL_CLOCKWISE                                        (0x504) /** dial clockwise */
#define CAN_DLC_DATA_DIAL_CLOCKWISE                                       (7)

#define CAN_ID_DATA_DIAL_COUNTER_CLOCKWISE                                (0x505) /** dial counter clockwise */
#define CAN_DLC_DATA_DIAL_COUNTER_CLOCKWISE                               (7)

#define CAN_ID_DATA_DIAL_CLICK                                            (0x506) /** dial click */
#define CAN_DLC_DATA_DIAL_CLICK                                           (7)

#define CAN_ID_DATA_RFID_READ                                             (0x507) /** rfid read */
#define CAN_DLC_DATA_RFID_READ                                            (7)

#define CAN_ID_DATA_CONTACT_CLOSED                                        (0x508) /** contact closed */
#define CAN_DLC_DATA_CONTACT_CLOSED                                       (7)

#define CAN_ID_DATA_CONTACT_OPENED                                        (0x509) /** contact opened */
#define CAN_DLC_DATA_CONTACT_OPENED                                       (7)

#define CAN_ID_DATA_INTERNAL_TEMPERATURE                                  (0x50A) /** internal temperature */
#define CAN_DLC_DATA_INTERNAL_TEMPERATURE                                 (7)

#define CAN_ID_DATA_INTERNAL_PCB_VOLTS                                    (0x50B) /** internal pcb volts */
#define CAN_DLC_DATA_INTERNAL_PCB_VOLTS                                   (7)

#define CAN_ID_DATA_INTERNAL_PCB_CURRENT                                  (0x50C) /** internal pcb current */
#define CAN_DLC_DATA_INTERNAL_PCB_CURRENT                                 (7)

#define CAN_ID_DATA_EXTERNAL_TEMPERATURE                                  (0x50D) /** external temperature */
#define CAN_DLC_DATA_EXTERNAL_TEMPERATURE                                 (8)

#define CAN_ID_DATA_EXTERNAL_VOLTS                                        (0x50E) /** external volts */
#define CAN_DLC_DATA_EXTERNAL_VOLTS                                       (8)

#define CAN_ID_DATA_EXTERNAL_CURRENT                                      (0x50F) /** external current */
#define CAN_DLC_DATA_EXTERNAL_CURRENT                                     (8)

#define CAN_ID_DATA_AMBIENT_LIGHT_USE_PRIV_MSG                            (0x510) /** ambient light USE PRIV MSG */
#define CAN_DLC_DATA_AMBIENT_LIGHT_USE_PRIV_MSG                           (5)

#define CAN_ID_DATA_IMU_X_AXIS                                            (0x511) /** IMU X Axis USE PRIV MSG */
#define CAN_DLC_DATA_IMU_X_AXIS                                           (5)

#define CAN_ID_DATA_IMU_Y_AXIS                                            (0x512) /** IMU Y Axis USE PRIV MSG */
#define CAN_DLC_DATA_IMU_Y_AXIS                                           (5)

#define CAN_ID_DATA_IMU_Z_AXIS                                            (0x513) /** IMU Z Axis USE PRIV MSG */
#define CAN_DLC_DATA_IMU_Z_AXIS                                           (5)

#define CAN_ID_DATA_IMU_X_GYRO                                            (0x514) /** IMU X Gyro USE PRIV MSG */
#define CAN_DLC_DATA_IMU_X_GYRO                                           (5)

#define CAN_ID_DATA_IMU_Y_GYRO                                            (0x515) /** IMU Y Gyro USE PRIV MSG */
#define CAN_DLC_DATA_IMU_Y_GYRO                                           (5)

#define CAN_ID_DATA_IMU_Z_GYRO                                            (0x516) /** IMU Z Gyro USE PRIV MSG */
#define CAN_DLC_DATA_IMU_Z_GYRO                                           (5)

#define CAN_ID_DATA_IMU_TEMPERATURE                                       (0x517) /** IMU temperature */
#define CAN_DLC_DATA_IMU_TEMPERATURE                                      (8)

#define CAN_ID_DATA_ANALOG_KNOB_MV                                        (0x518) /** analog knob mv */
#define CAN_DLC_DATA_ANALOG_KNOB_MV                                       (7)

#define CAN_ID_DATA_OUTPUT_SWITCH_MOM_PUSH                                (0x519) /** output switch mom push */
#define CAN_DLC_DATA_OUTPUT_SWITCH_MOM_PUSH                               (7)

#define CAN_ID_DATA_NODE_CPU_TEMP                                         (0x51A) /** node cpu temp */
#define CAN_DLC_DATA_NODE_CPU_TEMP                                        (7)

#define CAN_ID_DATA_NODE_LAST_BOOT_TIMESTAMP                              (0x51B) /** node last boot timestamp */
#define CAN_DLC_DATA_NODE_LAST_BOOT_TIMESTAMP                             (8)

#define CAN_ID_DATA_NODE_PCB_TEMP                                         (0x51C) /** node pcb temp */
#define CAN_DLC_DATA_NODE_PCB_TEMP                                        (6)

#define CAN_ID_DATA_OUTPUT_SWITCH_STATE                                   (0x51D) /** output switch state */
#define CAN_DLC_DATA_OUTPUT_SWITCH_STATE                                  (5)

#define CAN_ID_DATA_RESERVED_51E                                          (0x51E) /** data reserved 51e */
#define CAN_DLC_DATA_RESERVED_51E                                         (5)

#define CAN_ID_DATA_OUTPUT_SWITCH_MODE                                    (0x51F) /** output switch mode */
#define CAN_DLC_DATA_OUTPUT_SWITCH_MODE                                   (6)

#define CAN_ID_DATA_DISPLAY_OFF                                           (0x520) /** display off */
#define CAN_DLC_DATA_DISPLAY_OFF                                          (5)

#define CAN_ID_DATA_DISPLAY_ON                                            (0x521) /** display on */
#define CAN_DLC_DATA_DISPLAY_ON                                           (5)

#define CAN_ID_DATA_DISPLAY_CLEAR                                         (0x522) /** display clear */
#define CAN_DLC_DATA_DISPLAY_CLEAR                                        (5)

#define CAN_ID_DATA_DISPLAY_MODE                                          (0x523) /** display mode */
#define CAN_DLC_DATA_DISPLAY_MODE                                         (6)

#define CAN_ID_DATA_ARGB_BUTTON_COLOR                                     (0x524) /** argb button color */
#define CAN_DLC_DATA_ARGB_BUTTON_COLOR                                    (7)

#define CAN_ID_DATA_ARGB_BUTTON_LED_MODE                                  (0x525) /** argb button led mode */
#define CAN_DLC_DATA_ARGB_BUTTON_LED_MODE                                 (7)

#define CAN_ID_DATA_RESERVED_52A                                          (0x52A) /** 0x52A reserved private msg for 64-bit sensor data */
#define CAN_DLC_DATA_RESERVED_52A                                         (8)

#define CAN_ID_DATA_RESERVED_52B                                          (0x52B) /** 0x52B reserved private msg for 64-bit sensor data */
#define CAN_DLC_DATA_RESERVED_52B                                         (8)

#define CAN_ID_DATA_RESERVED_52C                                          (0x52C) /** 0x52C reserved private msg for 64-bit sensor data */
#define CAN_DLC_DATA_RESERVED_52C                                         (8)

#define CAN_ID_DATA_RESERVED_52D                                          (0x52D) /** 0x52D reserved private msg for 64-bit sensor data */
#define CAN_DLC_DATA_RESERVED_52D                                         (8)

#define CAN_ID_DATA_RESERVED_52E                                          (0x52E) /** 0x52E reserved private msg for 64-bit sensor data */
#define CAN_DLC_DATA_RESERVED_52E                                         (8)

#define CAN_ID_DATA_RESERVED_52F                                          (0x52F) /** 0x52F reserved private msg for 64-bit sensor data */
#define CAN_DLC_DATA_RESERVED_52F                                         (8)

#define CAN_ID_DATA_RESERVED_530                                          (0x530) /** 0x530 reserved private msg for 64-bit sensor data */
#define CAN_DLC_DATA_RESERVED_530                                         (8)

#define CAN_ID_DATA_RESERVED_531                                          (0x531) /** 0x531 reserved private msg for 64-bit sensor data */
#define CAN_DLC_DATA_RESERVED_531                                         (8)

#define CAN_ID_DATA_RESERVED_532                                          (0x532) /** 0x532 reserved private msg for 64-bit sensor data */
#define CAN_DLC_DATA_RESERVED_532                                         (8)

#define CAN_ID_DATA_RESERVED_533                                          (0x533) /** 0x533 reserved private msg for 64-bit sensor data */
#define CAN_DLC_DATA_RESERVED_533                                         (8)

#define CAN_ID_DATA_RESERVED_534                                          (0x534) /** 0x534 reserved private msg for 64-bit sensor data */
#define CAN_DLC_DATA_RESERVED_534                                         (8)

#define CAN_ID_DATA_RESERVED_535                                          (0x535) /** 0x535 reserved private msg for 64-bit sensor data */
#define CAN_DLC_DATA_RESERVED_535                                         (8)

#define CAN_ID_DATA_RESERVED_536                                          (0x536) /** 0x536 reserved private msg for 64-bit sensor data */
#define CAN_DLC_DATA_RESERVED_536                                         (8)

#define CAN_ID_DATA_RESERVED_537                                          (0x537) /** 0x537 reserved private msg for 64-bit sensor data */
#define CAN_DLC_DATA_RESERVED_537                                         (8)

#define CAN_ID_DATA_RESERVED_538                                          (0x538) /** 0x538 reserved private msg for 64-bit sensor data */
#define CAN_DLC_DATA_RESERVED_538                                         (8)

#define CAN_ID_DATA_RESERVED_539                                          (0x539) /** 0x539 reserved private msg for 64-bit sensor data */
#define CAN_DLC_DATA_RESERVED_539                                         (8)

#define CAN_ID_DATA_RESERVED_53A                                          (0x53A) /** 0x53A reserved private msg for 64-bit sensor data */
#define CAN_DLC_DATA_RESERVED_53A                                         (8)

#define CAN_ID_DATA_RESERVED_53B                                          (0x53B) /** 0x53B reserved private msg for 64-bit sensor data */
#define CAN_DLC_DATA_RESERVED_53B                                         (8)

#define CAN_ID_DATA_RESERVED_53C                                          (0x53C) /** 0x53C reserved private msg for 64-bit sensor data */
#define CAN_DLC_DATA_RESERVED_53C                                         (8)

#define CAN_ID_DATA_RESERVED_53D                                          (0x53D) /** 0x53D reserved private msg for 64-bit sensor data */
#define CAN_DLC_DATA_RESERVED_53D                                         (8)

#define CAN_ID_DATA_RESERVED_53E                                          (0x53E) /** 0x53E reserved private msg for 64-bit sensor data */
#define CAN_DLC_DATA_RESERVED_53E                                         (8)

#define CAN_ID_DATA_RESERVED_53F                                          (0x53F) /** 0x53F reserved private msg for 64-bit sensor data */
#define CAN_DLC_DATA_RESERVED_53F                                         (8)

#define CAN_ID_DISP_ANALOG_LED_STRIP                                      (0x700) /** analog led strip */
#define CAN_DLC_DISP_ANALOG_LED_STRIP                                     (8)

#define CAN_ID_DISP_ARGBW_LED_STRIP                                       (0x701) /** argbw led strip */
#define CAN_DLC_DISP_ARGBW_LED_STRIP                                      (8)

#define CAN_ID_DISP_ARGB_LED_STRIP                                        (0x702) /** argb led strip */
#define CAN_DLC_DISP_ARGB_LED_STRIP                                       (8)

#define CAN_ID_DISP_RESERVED_703                                          (0x703) /** disp reserved 703 */
#define CAN_DLC_DISP_RESERVED_703                                         (8)

#define CAN_ID_DISP_RESERVED_704                                          (0x704) /** disp reserved 704 */
#define CAN_DLC_DISP_RESERVED_704                                         (8)

#define CAN_ID_DISP_OLED                                                  (0x705) /** non-touch oled display */
#define CAN_DLC_DISP_OLED                                                 (8)

#define CAN_ID_DISP_RESERVED_706                                          (0x706) /** disp reserved 706 */
#define CAN_DLC_DISP_RESERVED_706                                         (8)

#define CAN_ID_DISP_LCD                                                   (0x707) /** non-touch lcd display */
#define CAN_DLC_DISP_LCD                                                  (8)

#define CAN_ID_DISP_RESERVED_708                                          (0x708) /** disp reserved 708 */

#define CAN_ID_DISP_RESERVED_709                                          (0x709) /** disp reserved 709 */

#define CAN_ID_DISP_RESERVED_70A                                          (0x70A) /** disp reserved 70a */

#define CAN_ID_DISP_RESERVED_70B                                          (0x70B) /** disp reserved 70b */

#define CAN_ID_DISP_RESERVED_70C                                          (0x70C) /** disp reserved 70c */

#define CAN_ID_DISP_RESERVED_70D                                          (0x70D) /** disp reserved 70d */

#define CAN_ID_DISP_RESERVED_70E                                          (0x70E) /** disp reserved 70e */

#define CAN_ID_DISP_RESERVED_70F                                          (0x70F) /** disp reserved 70f */

#define CAN_ID_INPUT_NO_BACKLIGHT                                         (0x710) /** input no backlight */
#define CAN_DLC_INPUT_NO_BACKLIGHT                                        (7)

#define CAN_ID_INPUT_ARGB_BACKLIGHT                                       (0x711) /** input argb backlight */
#define CAN_DLC_INPUT_ARGB_BACKLIGHT                                      (7)

#define CAN_ID_INPUT_ANALOG_BACKLIGHT                                     (0x712) /** input analog backlight */
#define CAN_DLC_INPUT_ANALOG_BACKLIGHT                                    (7)

#define CAN_ID_INPUT_VIRTUAL                                              (0x713) /** input virtual */
#define CAN_DLC_INPUT_VIRTUAL                                             (7)

#define CAN_ID_INPUT_WITH_DISPLAY                                         (0x714) /** input with display */
#define CAN_DLC_INPUT_WITH_DISPLAY                                        (7)

#define CAN_ID_INPUT_ANALOG_KNOB                                          (0x715) /** analog knob input */
#define CAN_DLC_INPUT_ANALOG_KNOB                                         (7)

#define CAN_ID_INPUT_JOG_DIAL_CLICK                                       (0x716) /** jog dial with click */
#define CAN_DLC_INPUT_JOG_DIAL_CLICK                                      (7)

#define CAN_ID_INPUT_KEY_SWITCH                                           (0x717) /** key switch */
#define CAN_DLC_INPUT_KEY_SWITCH                                          (7)

#define CAN_ID_INPUT_MOTION_DET                                           (0x718) /** motion detector */
#define CAN_DLC_INPUT_MOTION_DET                                          (7)

#define CAN_ID_INPUT_CAP_TOUCH                                            (0x719) /** capacitive touch switch stand-alone */
#define CAN_DLC_INPUT_CAP_TOUCH                                           (7)

#define CAN_ID_INPUT_JOG_DIAL_NOCLICK                                     (0x71A) /** jog dial without click */
#define CAN_DLC_INPUT_JOG_DIAL_NOCLICK                                    (7)

#define CAN_ID_INPUT_RFID_READER                                          (0x71B) /** RFID reader input */
#define CAN_DLC_INPUT_RFID_READER                                         (7)

#define CAN_ID_BUTTON_CONTACT_PULL_DOWN                                   (0x71C) /** button contact pull down */
#define CAN_DLC_BUTTON_CONTACT_PULL_DOWN                                  (7)

#define CAN_ID_INPUT_CONTACT_PULL_UP                                      (0x71D) /** input contact pull up */
#define CAN_DLC_INPUT_CONTACT_PULL_UP                                     (7)

#define CAN_ID_INPUT_RESERVED_71E                                         (0x71E) /** input reserved 71e */
#define CAN_DLC_INPUT_RESERVED_71E                                        (5)

#define CAN_ID_INPUT_RESERVED_71F                                         (0x71F) /** input reserved 71f */
#define CAN_DLC_INPUT_RESERVED_71F                                        (5)

#define CAN_ID_INPUT_DIGITAL_TEMP                                         (0x720) /** input digital temp */
#define CAN_DLC_INPUT_DIGITAL_TEMP                                        (5)

#define CAN_ID_INPUT_K_TYPE_TEMP                                          (0x721) /** input k type temp */
#define CAN_DLC_INPUT_K_TYPE_TEMP                                         (5)

#define CAN_ID_NODE_LASTBOOT                                              (0x722) /** last boot timestamp */
#define CAN_DLC_NODE_LASTBOOT                                             (5)

#define CAN_ID_NODE_PCB_TEMP                                              (0x723) /** node pcb temp */
#define CAN_DLC_NODE_PCB_TEMP                                             (5)

#define CAN_ID_NODE_CPU_TEMP                                              (0x724) /** node cpu temp */
#define CAN_DLC_NODE_CPU_TEMP                                             (5)

#define CAN_ID_INPUT_EXT_VOLTAGE_SENSOR                                   (0x725) /** input ext voltage sensor */
#define CAN_DLC_INPUT_EXT_VOLTAGE_SENSOR                                  (5)

#define CAN_ID_NODE_INT_VOLTAGE_SENSOR                                    (0x726) /** node int voltage sensor */
#define CAN_DLC_NODE_INT_VOLTAGE_SENSOR                                   (5)

#define CAN_ID_NODE_INT_CURRENT_SENSOR                                    (0x727) /** node int current sensor */
#define CAN_DLC_NODE_INT_CURRENT_SENSOR                                   (5)

#define CAN_ID_INPUT_EXT_CURRENT_SHUNT                                    (0x728) /** input ext current shunt */
#define CAN_DLC_INPUT_EXT_CURRENT_SHUNT                                   (5)

#define CAN_ID_INPUT_EXT_CURRENT_HALL                                     (0x729) /** input ext current hall */
#define CAN_DLC_INPUT_EXT_CURRENT_HALL                                    (5)

#define CAN_ID_SENSOR_RESERVED_72A                                        (0x72A) /** sensor reserved 72a */
#define CAN_DLC_SENSOR_RESERVED_72A                                       (5)

#define CAN_ID_SENSOR_RESERVED_72B                                        (0x72B) /** sensor reserved 72b */
#define CAN_DLC_SENSOR_RESERVED_72B                                       (5)

#define CAN_ID_SENSOR_RESERVED_72C                                        (0x72C) /** sensor reserved 72c */
#define CAN_DLC_SENSOR_RESERVED_72C                                       (5)

#define CAN_ID_SENSOR_RESERVED_72D                                        (0x72D) /** sensor reserved 72d */
#define CAN_DLC_SENSOR_RESERVED_72D                                       (5)

#define CAN_ID_SENSOR_RESERVED_72E                                        (0x72E) /** sensor reserved 72e */
#define CAN_DLC_SENSOR_RESERVED_72E                                       (5)

#define CAN_ID_SENSOR_RESERVED_72F                                        (0x72F) /** sensor reserved 72f */
#define CAN_DLC_SENSOR_RESERVED_72F                                       (5)

#define CAN_ID_INPUT_AMBIENT_LIGHT                                        (0x730) /** input ambient light */
#define CAN_DLC_INPUT_AMBIENT_LIGHT                                       (5)

#define CAN_ID_IMU_X_AXIS_SENSOR                                          (0x731) /** IMU X Axis sensor */
#define CAN_DLC_IMU_X_AXIS_SENSOR                                         (5)

#define CAN_ID_IMU_Y_AXIS_SENSOR                                          (0x732) /** IMU Y Axis sensor */
#define CAN_DLC_IMU_Y_AXIS_SENSOR                                         (5)

#define CAN_ID_IMU_Z_AXIS_SENSOR                                          (0x733) /** IMU Z Axis sensor */
#define CAN_DLC_IMU_Z_AXIS_SENSOR                                         (5)

#define CAN_ID_IMU_X_GYRO_SENSOR                                          (0x734) /** IMU X Gyro sensor */
#define CAN_DLC_IMU_X_GYRO_SENSOR                                         (5)

#define CAN_ID_IMU_Y_GYRO_SENSOR                                          (0x735) /** IMU Y Gyro sensor */
#define CAN_DLC_IMU_Y_GYRO_SENSOR                                         (5)

#define CAN_ID_IMU_Z_GYRO_SENSOR                                          (0x736) /** IMU Z Gyro sensor */
#define CAN_DLC_IMU_Z_GYRO_SENSOR                                         (5)

#define CAN_ID_IMU_TEMP_SENSOR                                            (0x737) /** IMU temp sensor */
#define CAN_DLC_IMU_TEMP_SENSOR                                           (5)

#define CAN_ID_GPS_UTC_TIME                                               (0x738) /** GPS utc time */
#define CAN_DLC_GPS_UTC_TIME                                              (5)

#define CAN_ID_GPS_LATITUDE                                               (0x739) /** GPS latitude */
#define CAN_DLC_GPS_LATITUDE                                              (5)

#define CAN_ID_GPS_NS_IND                                                 (0x73A) /** GPS NS IND */
#define CAN_DLC_GPS_NS_IND                                                (5)

#define CAN_ID_GPS_LONGITUDE                                              (0x73B) /** GPS longitude */
#define CAN_DLC_GPS_LONGITUDE                                             (5)

#define CAN_ID_GPS_EW_IND                                                 (0x73C) /** GPS EW IND */
#define CAN_DLC_GPS_EW_IND                                                (5)

#define CAN_ID_GPS_ALTITUDE                                               (0x73D) /** GPS altitude */
#define CAN_DLC_GPS_ALTITUDE                                              (5)

#define CAN_ID_GPS_STATUS                                                 (0x73E) /** GPS status */
#define CAN_DLC_GPS_STATUS                                                (5)

#define CAN_ID_SENSOR2_RESERVED_73F                                       (0x73F) /** sensor2 reserved 73f */

#define CAN_ID_OUT_HIGH_CURRENT_SW                                        (0x740) /** high current solid state switch */
#define CAN_DLC_OUT_HIGH_CURRENT_SW                                       (6)

#define CAN_ID_OUT_LOW_CURRENT_SW                                         (0x741) /** low current solid state switch */
#define CAN_DLC_OUT_LOW_CURRENT_SW                                        (6)

#define CAN_ID_OUT_OPEN_DRAIN                                             (0x742) /** open drain output */
#define CAN_DLC_OUT_OPEN_DRAIN                                            (6)

#define CAN_ID_OUT_MECH_RELAY                                             (0x743) /** mechanical relay */
#define CAN_DLC_OUT_MECH_RELAY                                            (6)

#define CAN_ID_OUT_RESERVED_744                                           (0x744) /** out reserved 744 */

#define CAN_ID_OUT_RESERVED_745                                           (0x745) /** out reserved 745 */

#define CAN_ID_OUT_RESERVED_746                                           (0x746) /** out reserved 746 */

#define CAN_ID_OUT_RESERVED_747                                           (0x747) /** out reserved 747 */

#define CAN_ID_OUT_RESERVED_748                                           (0x748) /** out reserved 748 */

#define CAN_ID_OUT_RESERVED_749                                           (0x749) /** out reserved 749 */

#define CAN_ID_OUT_RESERVED_74A                                           (0x74A) /** out reserved 74a */

#define CAN_ID_OUT_RESERVED_74B                                           (0x74B) /** out reserved 74b */

#define CAN_ID_OUT_RESERVED_74C                                           (0x74C) /** out reserved 74c */

#define CAN_ID_OUT_RESERVED_74D                                           (0x74D) /** out reserved 74d */

#define CAN_ID_OUT_RESERVED_74E                                           (0x74E) /** out reserved 74e */

#define CAN_ID_OUT_RESERVED_74F                                           (0x74F) /** out reserved 74f */

#define CAN_ID_BOX_SW_3GANG                                               (0x780) /** 3 gang switch box, 2 high, 1 low */
#define CAN_DLC_BOX_SW_3GANG                                              (6)

#define CAN_ID_BOX_SW_4GANG                                               (0x781) /** 4-gang switch box, 2 high, 2 low */
#define CAN_DLC_BOX_SW_4GANG                                              (6)

#define CAN_ID_BOX_SW_6GANG_HIGH                                          (0x782) /** 6-gang switch box, 4 high, 2 low */
#define CAN_DLC_BOX_SW_6GANG_HIGH                                         (6)

#define CAN_ID_BOX_SW_6GANG_LOW                                           (0x783) /** 6-gang switch box, 2 high, 4 low */
#define CAN_DLC_BOX_SW_6GANG_LOW                                          (6)

#define CAN_ID_BOX_SW_2GANG_HIGH                                          (0x784) /** 2-gang switch box, 2 high */
#define CAN_DLC_BOX_SW_2GANG_HIGH                                         (6)

#define CAN_ID_BOX_SW_2GANG_LOW                                           (0x785) /** 2-gang switch box, 2 low */
#define CAN_DLC_BOX_SW_2GANG_LOW                                          (6)

#define CAN_ID_BOX_MULTI_4XTEMP                                           (0x786) /** 4-digital multi temp input box */
#define CAN_DLC_BOX_MULTI_4XTEMP                                          (6)

#define CAN_ID_BOX_SW_4RELAY                                              (0x787) /** 4-gang relay output box */
#define CAN_DLC_BOX_SW_4RELAY                                             (6)

#define CAN_ID_BOX_MULTI_TVA                                              (0x788) /** temp, volt, current input box */
#define CAN_DLC_BOX_MULTI_TVA                                             (6)

#define CAN_ID_BOX_SW_8RELAY                                              (0x789) /** 8-gang relay output box */
#define CAN_DLC_BOX_SW_8RELAY                                             (6)

#define CAN_ID_BOX_MULTI_4X4IO                                            (0x78A) /** input - output box, 4 in, 4 out */
#define CAN_DLC_BOX_MULTI_4X4IO                                           (6)

#define CAN_ID_BOX_MULTI_IO                                               (0x78B) /** input - output box, multiple options */
#define CAN_DLC_BOX_MULTI_IO                                              (6)

#define CAN_ID_BOX_RESERVED_78C                                           (0x78C) /** box reserved 78c */
#define CAN_DLC_BOX_RESERVED_78C                                          (6)

#define CAN_ID_BOX_RESERVED_78D                                           (0x78D) /** box reserved 78d */
#define CAN_DLC_BOX_RESERVED_78D                                          (6)

#define CAN_ID_BOX_RESERVED_78E                                           (0x78E) /** box reserved 78e */
#define CAN_DLC_BOX_RESERVED_78E                                          (6)

#define CAN_ID_BOX_RESERVED_78F                                           (0x78F) /** box reserved 78f */
#define CAN_DLC_BOX_RESERVED_78F                                          (6)

#define CAN_ID_IFACE_8X4_ARGB_KEYPAD                                      (0x790) /** 8x4 argb keypad */
#define CAN_DLC_IFACE_8X4_ARGB_KEYPAD                                     (6)

#define CAN_ID_IFACE_4X4_ARGB_KEYPAD                                      (0x791) /** 4x4 argb keypad */
#define CAN_DLC_IFACE_4X4_ARGB_KEYPAD                                     (6)

#define CAN_ID_IFACE_TOUCHSCREEN_TYPE_A                                   (0x792) /** touchscreen type a */
#define CAN_DLC_IFACE_TOUCHSCREEN_TYPE_A                                  (6)

#define CAN_ID_IFACE_TOUCHSCREEN_TYPE_B                                   (0x793) /** touchscreen type b */
#define CAN_DLC_IFACE_TOUCHSCREEN_TYPE_B                                  (6)

#define CAN_ID_IFACE_NEXTION_TYPE_A                                       (0x794) /** nextion type a */
#define CAN_DLC_IFACE_NEXTION_TYPE_A                                      (6)

#define CAN_ID_IFACE_NEXTION_TYPE_B                                       (0x795) /** nextion type b */
#define CAN_DLC_IFACE_NEXTION_TYPE_B                                      (6)

#define CAN_ID_IFACE_RESERVED_796                                         (0x796) /** iface reserved 796 */
#define CAN_DLC_IFACE_RESERVED_796                                        (6)

#define CAN_ID_IFACE_RESERVED_797                                         (0x797) /** iface reserved 797 */
#define CAN_DLC_IFACE_RESERVED_797                                        (6)

#define CAN_ID_IFACE_RESERVED_798                                         (0x798) /** iface reserved 798 */

#define CAN_ID_IFACE_6_AXIS_IMU                                           (0x799) /** 6 axis imu */
#define CAN_DLC_IFACE_6_AXIS_IMU                                          (6)

#define CAN_ID_IFACE_3X5_BUTTON_BOX                                       (0x79A) /** 3x5 button box */
#define CAN_DLC_IFACE_3X5_BUTTON_BOX                                      (6)

#define CAN_ID_IFACE_4X6_BUTTON_BOX                                       (0x79B) /** 4x6 button box */
#define CAN_DLC_IFACE_4X6_BUTTON_BOX                                      (6)

#define CAN_ID_IFACE_RESERVED_79C                                         (0x79C) /** iface reserved 79c */

#define CAN_ID_IFACE_RESERVED_79D                                         (0x79D) /** iface reserved 79d */

#define CAN_ID_IFACE_RESERVED_79E                                         (0x79E) /** iface reserved 79e */

#define CAN_ID_IFACE_RESERVED_79F                                         (0x79F) /** iface reserved 79f */

#endif /* CANBUS_MSG_H_ */