/**
 * @file canbus_msg.h
 * @brief Autogenerated CAN definitions - Generated on 2026-04-03 20:55:28
 * @note DO NOT EDIT MANUALLY
 */
#ifndef CANBUS_MSG_H_
#define CANBUS_MSG_H_

#include <stdint.h>

/* ========================================================================== */
/* --- CAN MESSAGE IDS AND DLCS ---                                           */
/* ========================================================================== */
#define CANERR_OVER_CURRENT_ID                                            (0x100) /**< error condition over current */
#define CANERR_OVER_CURRENT_DLC                                           (8)

#define CANERR_OVER_VOLTAGE_ID                                            (0x101) /**< error condition over temp */
#define CANERR_OVER_VOLTAGE_DLC                                           (8)

#define CANNERR_OVER_VOLTAGE_ID                                           (0x102) /**< error condition over volt */
#define CANNERR_OVER_VOLTAGE_DLC                                          (8)

#define CANERR_GEN_ALARM_ID                                               (0x103) /**< general alarm */
#define CANERR_GEN_ALARM_DLC                                              (8)

#define CANERR_STORED_ERROR_ID                                            (0x104) /**< node has a stored error to transmit */
#define CANERR_STORED_ERROR_DLC                                           (8)

#define CANERR_RESERVED_105_ID                                            (0x105) /**< canerr reserved 105 */
#define CANERR_RESERVED_105_DLC                                           (4)

#define CANERR_RESERVED_106_ID                                            (0x106) /**< canerr reserved 106 */
#define CANERR_RESERVED_106_DLC                                           (4)

#define CANERR_RESERVED_107_ID                                            (0x107) /**< canerr reserved 107 */
#define CANERR_RESERVED_107_DLC                                           (4)

#define CANERR_RESERVED_108_ID                                            (0x108) /**< canerr reserved 108 */
#define CANERR_RESERVED_108_DLC                                           (4)

#define CANERR_RESERVED_109_ID                                            (0x109) /**< canerr reserved 109 */
#define CANERR_RESERVED_109_DLC                                           (4)

#define SW_RESERVED_110_ID                                                (0x110) /**< sw reserved 110 */
#define SW_RESERVED_110_DLC                                               (4)

#define SW_RESERVED_111_ID                                                (0x111) /**< sw reserved 111 */
#define SW_RESERVED_111_DLC                                               (4)

#define SW_SET_MODE_ID                                                    (0x112) /**< set switch mode */
#define SW_SET_MODE_DLC                                                   (6)

#define SW_SET_OFF_ID                                                     (0x113) /**< switch off */
#define SW_SET_OFF_DLC                                                    (5)

#define SW_SET_ON_ID                                                      (0x114) /**< switch on */
#define SW_SET_ON_DLC                                                     (5)

#define SW_MOM_PRESS_ID                                                   (0x115) /**< switch momentary press */
#define SW_MOM_PRESS_DLC                                                  (5)

#define SW_SET_MOM_DUR_ID                                                 (0x116) /**< set momentary switch duration ms */
#define SW_SET_MOM_DUR_DLC                                                (6)

#define SW_SET_PWM_DUTY_ID                                                (0x117) /**< switch set pwm duty */
#define SW_SET_PWM_DUTY_DLC                                               (6)

#define SW_SET_PWM_FREQ_ID                                                (0x118) /**< switch set pwm freq */
#define SW_SET_PWM_FREQ_DLC                                               (6)

#define SW_SET_BLINK_DELAY_ID                                             (0x119) /**< switch set blink delay in tenths of a second 1-100 */
#define SW_SET_BLINK_DELAY_DLC                                            (6)

#define SW_SET_STROBE_PAT_ID                                              (0x11A) /**< switch set strobe pattern */
#define SW_SET_STROBE_PAT_DLC                                             (6)

#define SW_SET_STATE_MEM_ID                                               (0x11B) /**< enable / disable switch last state memory */
#define SW_SET_STATE_MEM_DLC                                              (6)

#define SW_RESERVED_11C_ID                                                (0x11C) /**< sw reserved 11c */
#define SW_RESERVED_11C_DLC                                               (4)

#define SW_RESERVED_11D_ID                                                (0x11D) /**< sw reserved 11d */
#define SW_RESERVED_11D_DLC                                               (4)

#define SW_RESERVED_11E_ID                                                (0x11E) /**< sw reserved 11e */
#define SW_RESERVED_11E_DLC                                               (4)

#define SW_RESERVED_11F_ID                                                (0x11F) /**< sw reserved 11f */
#define SW_RESERVED_11F_DLC                                               (4)

#define SW_RESERVED_13A_ID                                                (0x13A) /**< sw reserved 13a */
#define SW_RESERVED_13A_DLC                                               (4)

#define SW_RESERVED_13B_ID                                                (0x13B) /**< sw reserved 13b */
#define SW_RESERVED_13B_DLC                                               (4)

#define SW_RESERVED_13C_ID                                                (0x13C) /**< sw reserved 13c */
#define SW_RESERVED_13C_DLC                                               (4)

#define SW_RESERVED_13D_ID                                                (0x13D) /**< sw reserved 13d */
#define SW_RESERVED_13D_DLC                                               (4)

#define SW_RESERVED_13E_ID                                                (0x13E) /**< sw reserved 13e */
#define SW_RESERVED_13E_DLC                                               (4)

#define SW_RESERVED_13F_ID                                                (0x13F) /**< sw reserved 13f */
#define SW_RESERVED_13F_DLC                                               (4)

#define SET_DISPLAY_OFF_ID                                                (0x200) /**< set display off */
#define SET_DISPLAY_OFF_DLC                                               (5)

#define SET_DISPLAY_ON_ID                                                 (0x201) /**< set display on */
#define SET_DISPLAY_ON_DLC                                                (5)

#define SET_DISPLAY_CLEAR_ID                                              (0x202) /**< set display clear */
#define SET_DISPLAY_CLEAR_DLC                                             (5)

#define SET_DISPLAY_FLASH_ID                                              (0x203) /**< set display flash */
#define SET_DISPLAY_FLASH_DLC                                             (6)

#define SET_DISPLAY_BACKLIGHT_COLOR_ID                                    (0x204) /**< set display backlight color */
#define SET_DISPLAY_BACKLIGHT_COLOR_DLC                                   (6)

#define SET_DISPLAY_BACKLIGHT_BRIGHTNESS_ID                               (0x205) /**< set display backlight brightness */
#define SET_DISPLAY_BACKLIGHT_BRIGHTNESS_DLC                              (6)

#define REQ_DISPLAY_CONFIG_ID                                             (0x206) /**< req display config */
#define REQ_DISPLAY_CONFIG_DLC                                            (7)

#define REQ_DISPLAY_DATA_ID                                               (0x207) /**< req display data */
#define REQ_DISPLAY_DATA_DLC                                              (7)

#define SET_OLED_FIELD_COLOR_ID                                           (0x208) /**< set oled field color */
#define SET_OLED_FIELD_COLOR_DLC                                          (6)

#define SET_OLED_FIELD_BLINK_ID                                           (0x209) /**< set oled field blink */
#define SET_OLED_FIELD_BLINK_DLC                                          (7)

#define SET_OLED_FIELD_STROBE_ID                                          (0x20A) /**< set oled field strobe */
#define SET_OLED_FIELD_STROBE_DLC                                         (6)

#define SET_DISPLAY_RESERVED_20B_ID                                       (0x20B) /**< set display reserved 20b */
#define SET_DISPLAY_RESERVED_20B_DLC                                      (4)

#define SET_DISPLAY_RESERVED_20C_ID                                       (0x20C) /**< set display reserved 20c */
#define SET_DISPLAY_RESERVED_20C_DLC                                      (4)

#define DISPLAY_DATA_MSG_ID                                               (0x20D) /**< display data msg */
#define DISPLAY_DATA_MSG_DLC                                              (8)

#define DISPLAY_DATA_ACK_ID                                               (0x20E) /**< display data ack */
#define DISPLAY_DATA_ACK_DLC                                              (8)

#define SET_DISPLAY_RESERVED_20F_ID                                       (0x20F) /**< set display reserved 20f */
#define SET_DISPLAY_RESERVED_20F_DLC                                      (4)

#define SET_ARGB_STRIP_COLOR_ID                                           (0x210) /**< set argb strip color */
#define SET_ARGB_STRIP_COLOR_DLC                                          (6)

#define SET_ARGBW_STRIP_COLOR_ID                                          (0x211) /**< set argbw strip color */
#define SET_ARGBW_STRIP_COLOR_DLC                                         (6)

#define SET_ANALOG_STRIP_COLOR_ID                                         (0x212) /**< set analog strip color */
#define SET_ANALOG_STRIP_COLOR_DLC                                        (8)

#define SET_ADDR_STRIP_EFFECT_ID                                          (0x213) /**< set addr strip effect */
#define SET_ADDR_STRIP_EFFECT_DLC                                         (6)

#define SET_LED_STRIP_BRIGHTNESS_ID                                       (0x214) /**< set led strip brightness */
#define SET_LED_STRIP_BRIGHTNESS_DLC                                      (6)

#define SET_LED_STRIP_OFF_ID                                              (0x215) /**< set led strip off */
#define SET_LED_STRIP_OFF_DLC                                             (5)

#define SET_LED_STRIP_ON_ID                                               (0x216) /**< set led strip on */
#define SET_LED_STRIP_ON_DLC                                              (5)

#define SET_LED_RESERVED_217_ID                                           (0x217) /**< set led reserved 217 */
#define SET_LED_RESERVED_217_DLC                                          (4)

#define SET_LED_RESERVED_218_ID                                           (0x218) /**< set led reserved 218 */
#define SET_LED_RESERVED_218_DLC                                          (4)

#define SET_LED_RESERVED_219_ID                                           (0x219) /**< set led reserved 219 */
#define SET_LED_RESERVED_219_DLC                                          (4)

#define SET_LED_RESERVED_21A_ID                                           (0x21A) /**< set led reserved 21a */
#define SET_LED_RESERVED_21A_DLC                                          (4)

#define SET_LED_RESERVED_21B_ID                                           (0x21B) /**< set led reserved 21b */
#define SET_LED_RESERVED_21B_DLC                                          (4)

#define SET_LED_RESERVED_21C_ID                                           (0x21C) /**< set led reserved 21c */
#define SET_LED_RESERVED_21C_DLC                                          (4)

#define SET_LED_RESERVED_21D_ID                                           (0x21D) /**< set led reserved 21d */
#define SET_LED_RESERVED_21D_DLC                                          (4)

#define SET_LED_RESERVED_21E_ID                                           (0x21E) /**< set led reserved 21e */
#define SET_LED_RESERVED_21E_DLC                                          (4)

#define SET_LED_RESERVED_21F_ID                                           (0x21F) /**< set led reserved 21f */
#define SET_LED_RESERVED_21F_DLC                                          (4)

#define SET_ARGB_BUTTON_COLOR_ID                                          (0x220) /**< set argb button color */
#define SET_ARGB_BUTTON_COLOR_DLC                                         (6)

#define SET_ARGB_BUTTON_LED_MODE_ID                                       (0x221) /**< set argb button led mode */
#define SET_ARGB_BUTTON_LED_MODE_DLC                                      (6)

#define SET_BUTTON_MODE_ID                                                (0x222) /**< set button mode 0 disabled, 1 toggle, 2 momentary */
#define SET_BUTTON_MODE_DLC                                               (4)

#define SET_BUTTON_RESERVED_223_ID                                        (0x223) /**< set button reserved 223 */
#define SET_BUTTON_RESERVED_223_DLC                                       (4)

#define SET_BUTTON_RESERVED_224_ID                                        (0x224) /**< set button reserved 224 */
#define SET_BUTTON_RESERVED_224_DLC                                       (4)

#define SET_BUTTON_RESERVED_225_ID                                        (0x225) /**< set button reserved 225 */
#define SET_BUTTON_RESERVED_225_DLC                                       (4)

#define SET_BUTTON_RESERVED_226_ID                                        (0x226) /**< set button reserved 226 */
#define SET_BUTTON_RESERVED_226_DLC                                       (4)

#define SET_BUTTON_RESERVED_227_ID                                        (0x227) /**< set button reserved 227 */
#define SET_BUTTON_RESERVED_227_DLC                                       (4)

#define SET_BUTTON_RESERVED_228_ID                                        (0x228) /**< set button reserved 228 */
#define SET_BUTTON_RESERVED_228_DLC                                       (4)

#define SET_BUTTON_RESERVED_229_ID                                        (0x229) /**< set button reserved 229 */
#define SET_BUTTON_RESERVED_229_DLC                                       (4)

#define SET_BUTTON_RESERVED_22A_ID                                        (0x22A) /**< set button reserved 22a */
#define SET_BUTTON_RESERVED_22A_DLC                                       (4)

#define SET_BUTTON_RESERVED_22B_ID                                        (0x22B) /**< set button reserved 22b */
#define SET_BUTTON_RESERVED_22B_DLC                                       (4)

#define SET_BUTTON_RESERVED_22C_ID                                        (0x22C) /**< set button reserved 22c */
#define SET_BUTTON_RESERVED_22C_DLC                                       (4)

#define SET_BUTTON_RESERVED_22D_ID                                        (0x22D) /**< set button reserved 22d */
#define SET_BUTTON_RESERVED_22D_DLC                                       (4)

#define SET_BUTTON_RESERVED_22E_ID                                        (0x22E) /**< set button reserved 22e */
#define SET_BUTTON_RESERVED_22E_DLC                                       (4)

#define SET_BUTTON_RESERVED_22F_ID                                        (0x22F) /**< set button reserved 22f */
#define SET_BUTTON_RESERVED_22F_DLC                                       (4)

#define CFG_ROUTE_BEGIN_ID                                                (0x300) /**< begin multi-frame route transfer */
#define CFG_ROUTE_BEGIN_DLC                                               (6)

#define CFG_ROUTE_DATA_ID                                                 (0x301) /**< 3-byte chunk of route_entry_t */
#define CFG_ROUTE_DATA_DLC                                                (8)

#define CFG_ROUTE_END_ID                                                  (0x302) /**< finalize and apply route entry */
#define CFG_ROUTE_END_DLC                                                 (6)

#define DATA_ROUTE_ACK_ID                                                 (0x303) /**< node sends this message after a route is received and saved */
#define DATA_ROUTE_ACK_DLC                                                (7)

#define ROUTE_RESERVED_304_ID                                             (0x304) /**< route reserved 304 */
#define ROUTE_RESERVED_304_DLC                                            (4)

#define ROUTE_RESERVED_305_ID                                             (0x305) /**< route reserved 305 */
#define ROUTE_RESERVED_305_DLC                                            (4)

#define ROUTE_RESERVED_306_ID                                             (0x306) /**< route reserved 306 */
#define ROUTE_RESERVED_306_DLC                                            (4)

#define ROUTE_RESERVED_307_ID                                             (0x307) /**< route reserved 307 */
#define ROUTE_RESERVED_307_DLC                                            (4)

#define REQ_ROUTE_LIST_ID                                                 (0x308) /**< request full routing table from node */
#define REQ_ROUTE_LIST_DLC                                                (4)

#define ROUTE_LIST_BEGIN_ID                                               (0x309) /**< node announces route count and chunk count */
#define ROUTE_LIST_BEGIN_DLC                                              (6)

#define ROUTE_LIST_DATA_ID                                                (0x30A) /**< 3-byte chunk of route_entry_t */
#define ROUTE_LIST_DATA_DLC                                               (8)

#define ROUTE_LIST_END_ID                                                 (0x30B) /**< node indicates routing table transfer complete */
#define ROUTE_LIST_END_DLC                                                (8)

#define ROUTE_RESERVED_30C_ID                                             (0x30C) /**< route reserved 30c */
#define ROUTE_RESERVED_30C_DLC                                            (4)

#define ROUTE_RESERVED_30D_ID                                             (0x30D) /**< route reserved 30d */
#define ROUTE_RESERVED_30D_DLC                                            (4)

#define ROUTE_RESERVED_30E_ID                                             (0x30E) /**< route reserved 30e */
#define ROUTE_RESERVED_30E_DLC                                            (4)

#define ROUTE_RESERVED_30F_ID                                             (0x30F) /**< route reserved 30f */
#define ROUTE_RESERVED_30F_DLC                                            (4)

#define CFG_ROUTE_DELETE_ID                                               (0x310) /**< delete route by index */
#define CFG_ROUTE_DELETE_DLC                                              (5)

#define CFG_ROUTE_PURGE_ID                                                (0x311) /**< delete all routes on node */
#define CFG_ROUTE_PURGE_DLC                                               (4)

#define CFG_ROUTE_WRITE_NVS_ID                                            (0x312) /**< save routing table to NVS */
#define CFG_ROUTE_WRITE_NVS_DLC                                           (4)

#define CFG_ROUTE_READ_NVS_ID                                             (0x313) /**< load routing table from NVS */
#define CFG_ROUTE_READ_NVS_DLC                                            (4)

#define ROUTE_RESERVED_314_ID                                             (0x314) /**< route reserved 314 */
#define ROUTE_RESERVED_314_DLC                                            (4)

#define ROUTE_RESERVED_315_ID                                             (0x315) /**< route reserved 315 */
#define ROUTE_RESERVED_315_DLC                                            (4)

#define ROUTE_RESERVED_316_ID                                             (0x316) /**< route reserved 316 */
#define ROUTE_RESERVED_316_DLC                                            (4)

#define ROUTE_RESERVED_317_ID                                             (0x317) /**< route reserved 317 */
#define ROUTE_RESERVED_317_DLC                                            (4)

#define ROUTE_RESERVED_318_ID                                             (0x318) /**< route reserved 318 */
#define ROUTE_RESERVED_318_DLC                                            (4)

#define ROUTE_RESERVED_319_ID                                             (0x319) /**< route reserved 319 */
#define ROUTE_RESERVED_319_DLC                                            (4)

#define ROUTE_RESERVED_31A_ID                                             (0x31A) /**< route reserved 31a */
#define ROUTE_RESERVED_31A_DLC                                            (4)

#define ROUTE_RESERVED_31B_ID                                             (0x31B) /**< route reserved 31b */
#define ROUTE_RESERVED_31B_DLC                                            (4)

#define ROUTE_RESERVED_31C_ID                                             (0x31C) /**< route reserved 31c */
#define ROUTE_RESERVED_31C_DLC                                            (4)

#define ROUTE_RESERVED_31D_ID                                             (0x31D) /**< route reserved 31d */
#define ROUTE_RESERVED_31D_DLC                                            (4)

#define ROUTE_RESERVED_31E_ID                                             (0x31E) /**< route reserved 31e */
#define ROUTE_RESERVED_31E_DLC                                            (4)

#define ROUTE_RESERVED_31F_ID                                             (0x31F) /**< route reserved 31f */
#define ROUTE_RESERVED_31F_DLC                                            (4)

#define PRODUCER_RESERVED_320_ID                                          (0x320) /**< producer reserved 320 */
#define PRODUCER_RESERVED_320_DLC                                         (4)

#define CFG_PRODUCER_CFG_ID                                               (0x321) /**< Configure a single producer submodule */
#define CFG_PRODUCER_CFG_DLC                                              (8)

#define CFG_PRODUCER_WRITE_NVS_ID                                         (0x322) /**< Commit producer config to NVS. */
#define CFG_PRODUCER_WRITE_NVS_DLC                                        (4)

#define CFG_PRODUCER_READ_NVS_ID                                          (0x323) /**< Request producer config for all submodules */
#define CFG_PRODUCER_READ_NVS_DLC                                         (4)

#define REQ_PRODUCER_CFG_ID                                               (0x324) /**< Request producer config  for idx */
#define REQ_PRODUCER_CFG_DLC                                              (5)

#define RESP_PRODUCER_CFG_ID                                              (0x325) /**< Node responds with requested data using this message id */
#define RESP_PRODUCER_CFG_DLC                                             (8)

#define CFG_PRODUCER_PURGE_ID                                             (0x326) /**< Purge the producer list */
#define CFG_PRODUCER_PURGE_DLC                                            (4)

#define CFG_PRODUCER_DEFAULTS_ID                                          (0x327) /**< Reset the producer at idx to defaults */
#define CFG_PRODUCER_DEFAULTS_DLC                                         (5)

#define CFG_PRODUCER_APPLY_ID                                             (0x328) /**< NO-OP Producer config is applied instantly */
#define CFG_PRODUCER_APPLY_DLC                                            (4)

#define CFG_PRODUCER_DELETE_ID                                            (0x329) /**< Delete the producer at idx */
#define CFG_PRODUCER_DELETE_DLC                                           (5)

#define CFG_PRODUCER_ENABLE_ID                                            (0x32A) /**< Enable the producer at idx */
#define CFG_PRODUCER_ENABLE_DLC                                           (5)

#define CFG_PRODUCER_DISABLE_ID                                           (0x32B) /**< Disable the producer at idx */
#define CFG_PRODUCER_DISABLE_DLC                                          (5)

#define CFG_PRODUCER_TOGGLE_ID                                            (0x32C) /**< Toggle operation of producer at idx */
#define CFG_PRODUCER_TOGGLE_DLC                                           (5)

#define REQ_PRODUCER_LIST_ID                                              (0x32D) /**< Ask the node to dump the entire producer cfg list */
#define REQ_PRODUCER_LIST_DLC                                             (4)

#define PRODUCER_LIST_BEGIN_ID                                            (0x32E) /**< Node will announce the count of defined producers */
#define PRODUCER_LIST_BEGIN_DLC                                           (5)

#define PRODUCER_LIST_DATA_ID                                             (0x32F) /**< Producer cfg data for index */
#define PRODUCER_LIST_DATA_DLC                                            (8)

#define PRODUCER_LIST_END_ID                                              (0x330) /**< Node will announce the end of the defined producers list */
#define PRODUCER_LIST_END_DLC                                             (5)

#define PRODUCER_RESERVED_331_ID                                          (0x331) /**< producer reserved 331 */
#define PRODUCER_RESERVED_331_DLC                                         (4)

#define PRODUCER_RESERVED_332_ID                                          (0x332) /**< producer reserved 332 */
#define PRODUCER_RESERVED_332_DLC                                         (4)

#define ACK_INTRO_ID                                                      (0x400) /**< acknowledge introduction, clear flag on remote device */
#define ACK_INTRO_DLC                                                     (4)

#define REQ_NODE_INTRO_ID                                                 (0x401) /**< general intro request for all node types */
#define REQ_NODE_INTRO_DLC                                                (4)

#define MSG_NORM_OPER_ID                                                  (0x402) /**< message to all nodes to being normal operation, sent after introduction and enumeration are complete */
#define MSG_NORM_OPER_DLC                                                 (4)

#define MSG_HALT_OPER_ID                                                  (0x403) /**< message to all nodes to stop transmitting messages and wait for instructions */
#define MSG_HALT_OPER_DLC                                                 (4)

#define REQ_NODECHECK_ID                                                  (0x404) /**< remote nodes should respond with their node id and last boot timestamp */
#define REQ_NODECHECK_DLC                                                 (4)

#define REQ_HEALTHCHECK_ID                                                (0x405) /**< remote nodes should respond with diagnostic sensor data */
#define REQ_HEALTHCHECK_DLC                                               (4)

#define REQ_IFACE_ID                                                      (0x406) /**< req interfaces node include buttons, displays leds and sensors */
#define REQ_IFACE_DLC                                                     (4)

#define REQ_SWITCHBOX_ID                                                  (0x407) /**< req switch boxes nodes include anything that controls a load */
#define REQ_SWITCHBOX_DLC                                                 (4)

#define REQ_RESERVED_408_ID                                               (0x408) /**< req reserved 408 */
#define REQ_RESERVED_408_DLC                                              (4)

#define REQ_RESERVED_409_ID                                               (0x409) /**< req reserved 409 */
#define REQ_RESERVED_409_DLC                                              (4)

#define REQ_RESERVED_40A_ID                                               (0x40A) /**< req reserved 40a */
#define REQ_RESERVED_40A_DLC                                              (4)

#define REQ_RESERVED_40B_ID                                               (0x40B) /**< req reserved 40b */
#define REQ_RESERVED_40B_DLC                                              (4)

#define DATA_EPOCH_ID                                                     (0x40C) /**< epoch timestamp from controller */
#define DATA_EPOCH_DLC                                                    (8)

#define DATA_SENSOR_MSG_ID                                                (0x40D) /**< controller assigned message id to use for transferring sensor data range 52A:53F */
#define DATA_SENSOR_MSG_DLC                                               (7)

#define REQ_RESERVED_40E_ID                                               (0x40E) /**< req reserved 40e */
#define REQ_RESERVED_40E_DLC                                              (4)

#define REQ_RESERVED_40F_ID                                               (0x40F) /**< req reserved 40f */
#define REQ_RESERVED_40F_DLC                                              (4)

#define REQ_DIGITAL_INPUTS_ID                                             (0x410) /**< req digital inputs (gpio type) */
#define REQ_DIGITAL_INPUTS_DLC                                            (4)

#define REQ_DIGITAL_OUTPUTS_ID                                            (0x411) /**< req digital outputs (gpio type) */
#define REQ_DIGITAL_OUTPUTS_DLC                                           (4)

#define REQ_DISPLAYS_ID                                                   (0x412) /**< req displays (eg lcd, oled, argb, led) */
#define REQ_DISPLAYS_DLC                                                  (4)

#define REQ_TEMP_SENSOR_ID                                                (0x413) /**< req temp sensor */
#define REQ_TEMP_SENSOR_DLC                                               (4)

#define REQ_VOLT_SENSOR_ID                                                (0x414) /**< req volt sensor */
#define REQ_VOLT_SENSOR_DLC                                               (4)

#define REQ_AMP_SENSOR_ID                                                 (0x415) /**< req amp sensor */
#define REQ_AMP_SENSOR_DLC                                                (4)

#define REQ_ANALOG_INPUTS_ID                                              (0x416) /**< req analog inputs */
#define REQ_ANALOG_INPUTS_DLC                                             (4)

#define REQ_AMBIENT_LIGHT_ID                                              (0x417) /**< req ambient light sensors */
#define REQ_AMBIENT_LIGHT_DLC                                             (4)

#define REQ_IMU_SENSORS_ID                                                (0x418) /**< req imu sensors */
#define REQ_IMU_SENSORS_DLC                                               (4)

#define REQ_RESERVED_419_ID                                               (0x419) /**< req reserved 419 */
#define REQ_RESERVED_419_DLC                                              (4)

#define REQ_RESERVED_41A_ID                                               (0x41A) /**< req reserved 41a */
#define REQ_RESERVED_41A_DLC                                              (4)

#define REQ_RESERVED_41B_ID                                               (0x41B) /**< req reserved 41b */
#define REQ_RESERVED_41B_DLC                                              (4)

#define REQ_RESERVED_41C_ID                                               (0x41C) /**< req reserved 41c */
#define REQ_RESERVED_41C_DLC                                              (4)

#define REQ_RESERVED_41D_ID                                               (0x41D) /**< req reserved 41d */
#define REQ_RESERVED_41D_DLC                                              (4)

#define REQ_RESERVED_41E_ID                                               (0x41E) /**< req reserved 41e */
#define REQ_RESERVED_41E_DLC                                              (4)

#define REQ_RESERVED_41F_ID                                               (0x41F) /**< req reserved 41f */
#define REQ_RESERVED_41F_DLC                                              (4)

#define CFG_RESERVED_420_ID                                               (0x420) /**< cfg reserved 420 */
#define CFG_RESERVED_420_DLC                                              (4)

#define CFG_SUB_FLAG_ADD_ID                                               (0x421) /**< add flag to submodule config */
#define CFG_SUB_FLAG_ADD_DLC                                              (6)

#define CFG_SUB_DATA_MSG_ID                                               (0x422) /**< configure sub-module data message */
#define CFG_SUB_DATA_MSG_DLC                                              (8)

#define CFG_SUB_INTRO_MSG_ID                                              (0x423) /**< configure sub-module intro message, this defines the sub module type */
#define CFG_SUB_INTRO_MSG_DLC                                             (8)

#define CFG_SUB_RAW_DATA_ID                                               (0x424) /**< cfg sub raw data */
#define CFG_SUB_RAW_DATA_DLC                                              (8)

#define CFG_SUB_FLAG_REMOVE_ID                                            (0x425) /**< remove flag from submodule config */
#define CFG_SUB_FLAG_REMOVE_DLC                                           (6)

#define CFG_NODE_DATA_MSG_ID                                              (0x426) /**< configure parent node data message (currently not implemented) */
#define CFG_NODE_DATA_MSG_DLC                                             (7)

#define CFG_NODE_INTRO_MSG_ID                                             (0x427) /**< configure parent node intro message */
#define CFG_NODE_INTRO_MSG_DLC                                            (7)

#define CFG_RESERVED_428_ID                                               (0x428) /**< cfg reserved 428 */
#define CFG_RESERVED_428_DLC                                              (4)

#define CFG_RESERVED_429_ID                                               (0x429) /**< cfg reserved 429 */
#define CFG_RESERVED_429_DLC                                              (4)

#define COLORPICKER_READ_NVS_ID                                           (0x42A) /**< colorpicker read routing from nvs */
#define COLORPICKER_READ_NVS_DLC                                          (4)

#define COLORPICKER_WRITE_NVS_ID                                          (0x42B) /**< colorpicker write routing to nvs */
#define COLORPICKER_WRITE_NVS_DLC                                         (4)

#define COLORPICKER_SEND_LIST_ID                                          (0x42C) /**< colorpicker send route list to master */
#define COLORPICKER_SEND_LIST_DLC                                         (4)

#define COLORPICKER_LIST_DATA_ID                                          (0x42D) /**< colorpicker list data message */
#define COLORPICKER_LIST_DATA_DLC                                         (8)

#define CFG_RESERVED_42E_ID                                               (0x42E) /**< cfg reserved 42e */
#define CFG_RESERVED_42E_DLC                                              (4)

#define CFG_RESERVED_42F_ID                                               (0x42F) /**< cfg reserved 42f */
#define CFG_RESERVED_42F_DLC                                              (4)

#define CFG_NET_RESERVED_430_ID                                           (0x430) /**< cfg net reserved 430 */
#define CFG_NET_RESERVED_430_DLC                                          (4)

#define CFG_NET_NODE_ADD_ID                                               (0x431) /**< Add remote node ID to the network submodule table */
#define CFG_NET_NODE_ADD_DLC                                              (8)

#define CFG_NET_NODE_DEL_ID                                               (0x432) /**< Delete remote node ID from the network submodule table */
#define CFG_NET_NODE_DEL_DLC                                              (8)

#define CFG_NET_NODE_DATA_ID                                              (0x433) /**< Send configuration data for a node in network submodule table */
#define CFG_NET_NODE_DATA_DLC                                             (8)

#define CFG_NET_RESERVED_434_ID                                           (0x434) /**< cfg net reserved 434 */
#define CFG_NET_RESERVED_434_DLC                                          (4)

#define CFG_NET_RESERVED_435_ID                                           (0x435) /**< cfg net reserved 435 */
#define CFG_NET_RESERVED_435_DLC                                          (4)

#define CFG_NET_RESERVED_436_ID                                           (0x436) /**< cfg net reserved 436 */
#define CFG_NET_RESERVED_436_DLC                                          (4)

#define CFG_NET_RESERVED_437_ID                                           (0x437) /**< cfg net reserved 437 */
#define CFG_NET_RESERVED_437_DLC                                          (4)

#define CFG_NET_RESERVED_438_ID                                           (0x438) /**< cfg net reserved 438 */
#define CFG_NET_RESERVED_438_DLC                                          (4)

#define CFG_NET_RESERVED_439_ID                                           (0x439) /**< cfg net reserved 439 */
#define CFG_NET_RESERVED_439_DLC                                          (4)

#define CFG_RESERVED_43A_ID                                               (0x43A) /**< cfg reserved 43a */
#define CFG_RESERVED_43A_DLC                                              (4)

#define CFG_RESERVED_43B_ID                                               (0x43B) /**< cfg reserved 43b */
#define CFG_RESERVED_43B_DLC                                              (4)

#define CFG_RESERVED_43C_ID                                               (0x43C) /**< cfg reserved 43c */
#define CFG_RESERVED_43C_DLC                                              (4)

#define CFG_RESERVED_43D_ID                                               (0x43D) /**< cfg reserved 43d */
#define CFG_RESERVED_43D_DLC                                              (4)

#define CFG_RESERVED_43E_ID                                               (0x43E) /**< cfg reserved 43e */
#define CFG_RESERVED_43E_DLC                                              (4)

#define CFG_RESERVED_43F_ID                                               (0x43F) /**< cfg reserved 43f */
#define CFG_RESERVED_43F_DLC                                              (4)

#define CFG_NVS_RESERVED_440_ID                                           (0x440) /**< cfg nvs reserved 440 */
#define CFG_NVS_RESERVED_440_DLC                                          (4)

#define CFG_WRITE_NVS_ID                                                  (0x441) /**< write nvs */
#define CFG_WRITE_NVS_DLC                                                 (6)

#define CFG_READ_NVS_ID                                                   (0x442) /**< read nvs */
#define CFG_READ_NVS_DLC                                                  (6)

#define CFG_ERASE_NVS_ID                                                  (0x443) /**< erase nvs */
#define CFG_ERASE_NVS_DLC                                                 (4)

#define CFG_SET_LOGLEVEL_ID                                               (0x444) /**< Configure the debug log level */
#define CFG_SET_LOGLEVEL_DLC                                              (5)

#define CFG_REBOOT_ID                                                     (0x445) /**< reboot node */
#define CFG_REBOOT_DLC                                                    (4)

#define REQ_ROUTE_TABLE_PRT_ID                                            (0x446) /**< Dump router table to the debug interface */
#define REQ_ROUTE_TABLE_PRT_DLC                                           (4)

#define REQ_NODEINFO_PRT_ID                                               (0x447) /**< Dump nodeInfo to the debug interface */
#define REQ_NODEINFO_PRT_DLC                                              (4)

#define REQ_TWAI_INFO_PRT_ID                                              (0x448) /**< Dump twai interface status to debug interface */
#define REQ_TWAI_INFO_PRT_DLC                                             (4)

#define CFG_NVS_RESERVED_449_ID                                           (0x449) /**< cfg nvs reserved 449 */
#define CFG_NVS_RESERVED_449_DLC                                          (4)

#define CFG_NVS_RESERVED_44A_ID                                           (0x44A) /**< cfg nvs reserved 44a */
#define CFG_NVS_RESERVED_44A_DLC                                          (4)

#define CFG_NVS_RESERVED_44B_ID                                           (0x44B) /**< cfg nvs reserved 44b */
#define CFG_NVS_RESERVED_44B_DLC                                          (4)

#define CFG_NVS_RESERVED_44C_ID                                           (0x44C) /**< cfg nvs reserved 44c */
#define CFG_NVS_RESERVED_44C_DLC                                          (4)

#define CFG_NVS_RESERVED_44D_ID                                           (0x44D) /**< cfg nvs reserved 44d */
#define CFG_NVS_RESERVED_44D_DLC                                          (4)

#define CFG_NVS_RESERVED_44E_ID                                           (0x44E) /**< cfg nvs reserved 44e */
#define CFG_NVS_RESERVED_44E_DLC                                          (4)

#define CFG_NVS_RESERVED_44F_ID                                           (0x44F) /**< cfg nvs reserved 44f */
#define CFG_NVS_RESERVED_44F_DLC                                          (4)

#define CFG_NVS_RESERVED_450_ID                                           (0x450) /**< cfg nvs reserved 450 */
#define CFG_NVS_RESERVED_450_DLC                                          (4)

#define CFG_BLINK_OUTPUT_ID                                               (0x451) /**< cfg blink output */
#define CFG_BLINK_OUTPUT_DLC                                              (8)

#define CFG_ANALOG_STRIP_ID                                               (0x452) /**< cfg analog strip */
#define CFG_ANALOG_STRIP_DLC                                              (8)

#define CFG_ARGB_STRIP_ID                                                 (0x453) /**< cfg argb strip */
#define CFG_ARGB_STRIP_DLC                                                (8)

#define CFG_DIGITAL_INPUT_ID                                              (0x454) /**< cfg digital input */
#define CFG_DIGITAL_INPUT_DLC                                             (8)

#define CFG_DIGITAL_OUTPUT_ID                                             (0x455) /**< cfg digital output */
#define CFG_DIGITAL_OUTPUT_DLC                                            (8)

#define CFG_ANALOG_INPUT_ID                                               (0x456) /**< cfg analog input */
#define CFG_ANALOG_INPUT_DLC                                              (8)

#define CFG_ANALOG_OUTPUT_ID                                              (0x457) /**< cfg analog output */
#define CFG_ANALOG_OUTPUT_DLC                                             (8)

#define CFG_PWM_OUTPUT_ID                                                 (0x458) /**< cfg pwm output */
#define CFG_PWM_OUTPUT_DLC                                                (8)

#define CFG_RESERVED_459_ID                                               (0x459) /**< cfg reserved 459 */
#define CFG_RESERVED_459_DLC                                              (4)

#define CFG_RESERVED_45A_ID                                               (0x45A) /**< cfg reserved 45a */
#define CFG_RESERVED_45A_DLC                                              (4)

#define CFG_RESERVED_45B_ID                                               (0x45B) /**< cfg reserved 45b */
#define CFG_RESERVED_45B_DLC                                              (4)

#define CFG_RESERVED_45C_ID                                               (0x45C) /**< cfg reserved 45c */
#define CFG_RESERVED_45C_DLC                                              (4)

#define CFG_RESERVED_45D_ID                                               (0x45D) /**< cfg reserved 45d */
#define CFG_RESERVED_45D_DLC                                              (4)

#define CFG_RESERVED_45E_ID                                               (0x45E) /**< cfg reserved 45e */
#define CFG_RESERVED_45E_DLC                                              (4)

#define CFG_RESERVED_45F_ID                                               (0x45F) /**< cfg reserved 45f */
#define CFG_RESERVED_45F_DLC                                              (4)

#define CFG_RESERVED_460_ID                                               (0x460) /**< cfg reserved 460 */
#define CFG_RESERVED_460_DLC                                              (4)

#define CFG_RESERVED_461_ID                                               (0x461) /**< cfg reserved 461 */
#define CFG_RESERVED_461_DLC                                              (4)

#define CFG_RESERVED_462_ID                                               (0x462) /**< cfg reserved 462 */
#define CFG_RESERVED_462_DLC                                              (4)

#define CFG_RESERVED_463_ID                                               (0x463) /**< cfg reserved 463 */
#define CFG_RESERVED_463_DLC                                              (4)

#define CFG_RESERVED_464_ID                                               (0x464) /**< cfg reserved 464 */
#define CFG_RESERVED_464_DLC                                              (4)

#define CFG_RESERVED_465_ID                                               (0x465) /**< cfg reserved 465 */
#define CFG_RESERVED_465_DLC                                              (4)

#define CFG_RESERVED_466_ID                                               (0x466) /**< cfg reserved 466 */
#define CFG_RESERVED_466_DLC                                              (4)

#define CFG_RESERVED_467_ID                                               (0x467) /**< cfg reserved 467 */
#define CFG_RESERVED_467_DLC                                              (4)

#define CFG_RESERVED_468_ID                                               (0x468) /**< cfg reserved 468 */
#define CFG_RESERVED_468_DLC                                              (4)

#define CFG_RESERVED_469_ID                                               (0x469) /**< cfg reserved 469 */
#define CFG_RESERVED_469_DLC                                              (4)

#define CFG_RESERVED_46A_ID                                               (0x46A) /**< cfg reserved 46a */
#define CFG_RESERVED_46A_DLC                                              (4)

#define CFG_RESERVED_46B_ID                                               (0x46B) /**< cfg reserved 46b */
#define CFG_RESERVED_46B_DLC                                              (4)

#define CFG_RESERVED_46C_ID                                               (0x46C) /**< cfg reserved 46c */
#define CFG_RESERVED_46C_DLC                                              (4)

#define CFG_RESERVED_46D_ID                                               (0x46D) /**< cfg reserved 46d */
#define CFG_RESERVED_46D_DLC                                              (4)

#define CFG_RESERVED_46E_ID                                               (0x46E) /**< cfg reserved 46e */
#define CFG_RESERVED_46E_DLC                                              (4)

#define CFG_RESERVED_46F_ID                                               (0x46F) /**< cfg reserved 46f */
#define CFG_RESERVED_46F_DLC                                              (4)

#define CFG_RESERVED_470_ID                                               (0x470) /**< cfg reserved 470 */
#define CFG_RESERVED_470_DLC                                              (4)

#define CFG_RESERVED_471_ID                                               (0x471) /**< cfg reserved 471 */
#define CFG_RESERVED_471_DLC                                              (4)

#define CFG_RESERVED_472_ID                                               (0x472) /**< cfg reserved 472 */
#define CFG_RESERVED_472_DLC                                              (4)

#define CFG_RESERVED_473_ID                                               (0x473) /**< cfg reserved 473 */
#define CFG_RESERVED_473_DLC                                              (4)

#define CFG_RESERVED_474_ID                                               (0x474) /**< cfg reserved 474 */
#define CFG_RESERVED_474_DLC                                              (4)

#define CFG_RESERVED_475_ID                                               (0x475) /**< cfg reserved 475 */
#define CFG_RESERVED_475_DLC                                              (4)

#define CFG_RESERVED_476_ID                                               (0x476) /**< cfg reserved 476 */
#define CFG_RESERVED_476_DLC                                              (4)

#define CFG_RESERVED_477_ID                                               (0x477) /**< cfg reserved 477 */
#define CFG_RESERVED_477_DLC                                              (4)

#define CFG_RESERVED_478_ID                                               (0x478) /**< cfg reserved 478 */
#define CFG_RESERVED_478_DLC                                              (4)

#define CFG_RESERVED_479_ID                                               (0x479) /**< cfg reserved 479 */
#define CFG_RESERVED_479_DLC                                              (4)

#define CFG_RESERVED_47A_ID                                               (0x47A) /**< cfg reserved 47a */
#define CFG_RESERVED_47A_DLC                                              (4)

#define CFG_RESERVED_47B_ID                                               (0x47B) /**< cfg reserved 47b */
#define CFG_RESERVED_47B_DLC                                              (4)

#define CFG_RESERVED_47C_ID                                               (0x47C) /**< cfg reserved 47c */
#define CFG_RESERVED_47C_DLC                                              (4)

#define CFG_RESERVED_47D_ID                                               (0x47D) /**< cfg reserved 47d */
#define CFG_RESERVED_47D_DLC                                              (4)

#define CFG_RESERVED_47E_ID                                               (0x47E) /**< cfg reserved 47e */
#define CFG_RESERVED_47E_DLC                                              (4)

#define CFG_RESERVED_47F_ID                                               (0x47F) /**< cfg reserved 47f */
#define CFG_RESERVED_47F_DLC                                              (4)

#define DATA_BUTTON_DOWN_ID                                               (0x500) /**< button down */
#define DATA_BUTTON_DOWN_DLC                                              (7)

#define DATA_BUTTON_UP_ID                                                 (0x501) /**< button up */
#define DATA_BUTTON_UP_DLC                                                (7)

#define DATA_KEYSWITCH_LOCK_ID                                            (0x502) /**< keyswitch lock */
#define DATA_KEYSWITCH_LOCK_DLC                                           (7)

#define DATA_KEYSWITCH_UNLOCK_ID                                          (0x503) /**< keyswitch unlock */
#define DATA_KEYSWITCH_UNLOCK_DLC                                         (7)

#define DATA_DIAL_CLOCKWISE_ID                                            (0x504) /**< dial clockwise */
#define DATA_DIAL_CLOCKWISE_DLC                                           (7)

#define DATA_DIAL_COUNTER_CLOCKWISE_ID                                    (0x505) /**< dial counter clockwise */
#define DATA_DIAL_COUNTER_CLOCKWISE_DLC                                   (7)

#define DATA_DIAL_CLICK_ID                                                (0x506) /**< dial click */
#define DATA_DIAL_CLICK_DLC                                               (7)

#define DATA_EXTERNAL_CURRENT_ID                                          (0x507) /**< external current */
#define DATA_EXTERNAL_CURRENT_DLC                                         (8)

#define DATA_CONTACT_CLOSED_ID                                            (0x508) /**< contact closed */
#define DATA_CONTACT_CLOSED_DLC                                           (7)

#define DATA_CONTACT_OPENED_ID                                            (0x509) /**< contact opened */
#define DATA_CONTACT_OPENED_DLC                                           (7)

#define DATA_INTERNAL_PCB_TEMP_ID                                         (0x50A) /**< internal pcb temp */
#define DATA_INTERNAL_PCB_TEMP_DLC                                        (8)

#define DATA_INTERNAL_PCB_VOLTS_ID                                        (0x50B) /**< internal pcb volts */
#define DATA_INTERNAL_PCB_VOLTS_DLC                                       (8)

#define DATA_INTERNAL_PCB_CURRENT_ID                                      (0x50C) /**< internal pcb current */
#define DATA_INTERNAL_PCB_CURRENT_DLC                                     (8)

#define DATA_EXTERNAL_TEMPERATURE_ID                                      (0x50D) /**< external temperature */
#define DATA_EXTERNAL_TEMPERATURE_DLC                                     (8)

#define DATA_EXTERNAL_VOLTS_ID                                            (0x50E) /**< external volts */
#define DATA_EXTERNAL_VOLTS_DLC                                           (8)

#define DATA_ADC_RAW_ID                                                   (0x50F) /**< adc raw */
#define DATA_ADC_RAW_DLC                                                  (7)

#define DATA_AMBIENT_LIGHT_USE_PRIV_MSG_ID                                (0x510) /**< ambient light USE PRIV MSG */
#define DATA_AMBIENT_LIGHT_USE_PRIV_MSG_DLC                               (5)

#define DATA_IMU_X_AXIS_ID                                                (0x511) /**< IMU X Axis USE PRIV MSG */
#define DATA_IMU_X_AXIS_DLC                                               (5)

#define DATA_IMU_Y_AXIS_ID                                                (0x512) /**< IMU Y Axis USE PRIV MSG */
#define DATA_IMU_Y_AXIS_DLC                                               (5)

#define DATA_IMU_Z_AXIS_ID                                                (0x513) /**< IMU Z Axis USE PRIV MSG */
#define DATA_IMU_Z_AXIS_DLC                                               (5)

#define DATA_IMU_X_GYRO_ID                                                (0x514) /**< IMU X Gyro USE PRIV MSG */
#define DATA_IMU_X_GYRO_DLC                                               (5)

#define DATA_IMU_Y_GYRO_ID                                                (0x515) /**< IMU Y Gyro USE PRIV MSG */
#define DATA_IMU_Y_GYRO_DLC                                               (5)

#define DATA_IMU_Z_GYRO_ID                                                (0x516) /**< IMU Z Gyro USE PRIV MSG */
#define DATA_IMU_Z_GYRO_DLC                                               (5)

#define DATA_IMU_TEMPERATURE_ID                                           (0x517) /**< IMU temperature */
#define DATA_IMU_TEMPERATURE_DLC                                          (8)

#define DATA_ANALOG_KNOB_MV_ID                                            (0x518) /**< analog knob mv */
#define DATA_ANALOG_KNOB_MV_DLC                                           (8)

#define DATA_DATA_RESERVED_519_ID                                         (0x519) /**< data reserved 519 */
#define DATA_DATA_RESERVED_519_DLC                                        (4)

#define DATA_NODE_CPU_TEMP_ID                                             (0x51A) /**< node cpu temp */
#define DATA_NODE_CPU_TEMP_DLC                                            (8)

#define DATA_NODE_BOOT_TIMESTAMP_ID                                       (0x51B) /**< node boot timestamp */
#define DATA_NODE_BOOT_TIMESTAMP_DLC                                      (8)

#define DATA_TOUCHSCREEN_EVENT_ID                                         (0x51C) /**< data touchscreen event */
#define DATA_TOUCHSCREEN_EVENT_DLC                                        (4)

#define DATA_RESERVED_51D_ID                                              (0x51D) /**< data reserved 51d */
#define DATA_RESERVED_51D_DLC                                             (8)

#define DATA_RESERVED_51E_ID                                              (0x51E) /**< data reserved 51e */
#define DATA_RESERVED_51E_DLC                                             (8)

#define DATA_RESERVED_51F_ID                                              (0x51F) /**< data reserved 51f */
#define DATA_RESERVED_51F_DLC                                             (8)

#define DATA_DISPLAY_OFF_ID                                               (0x520) /**< display off */
#define DATA_DISPLAY_OFF_DLC                                              (5)

#define DATA_DISPLAY_ON_ID                                                (0x521) /**< display on */
#define DATA_DISPLAY_ON_DLC                                               (5)

#define DATA_DISPLAY_CLEAR_ID                                             (0x522) /**< display clear */
#define DATA_DISPLAY_CLEAR_DLC                                            (5)

#define DATA_DISPLAY_MODE_ID                                              (0x523) /**< display mode */
#define DATA_DISPLAY_MODE_DLC                                             (6)

#define DATA_ARGB_BUTTON_COLOR_ID                                         (0x524) /**< argb button color */
#define DATA_ARGB_BUTTON_COLOR_DLC                                        (6)

#define DATA_ARGB_BUTTON_LED_MODE_ID                                      (0x525) /**< argb button led mode */
#define DATA_ARGB_BUTTON_LED_MODE_DLC                                     (7)

#define DATA_CONFIG_CRC_ID                                                (0x526) /**< data config crc */
#define DATA_CONFIG_CRC_DLC                                               (6)

#define DATA_CONFIG_TIMESTAMP_ID                                          (0x527) /**< data config timestamp */
#define DATA_CONFIG_TIMESTAMP_DLC                                         (8)

#define DATA_CFGWRITE_FAILED_ID                                           (0x528) /**< data cfgwrite failed */
#define DATA_CFGWRITE_FAILED_DLC                                          (6)

#define DATA_WIFI_RSSI_ID                                                 (0x529) /**< wifi rssi for nodes that support it */
#define DATA_WIFI_RSSI_DLC                                                (8)

#define DATA_RTOS_FREE_HEAP_ID                                            (0x52A) /**< freertos free heap memory */
#define DATA_RTOS_FREE_HEAP_DLC                                           (8)

#define DATA_RTOS_HIGH_WATER_ID                                           (0x52B) /**< freertos high water mark */
#define DATA_RTOS_HIGH_WATER_DLC                                          (8)

#define DATA_RESET_REASON_ID                                              (0x52C) /**< read last reset reason */
#define DATA_RESET_REASON_DLC                                             (8)

#define DATA_BROWNOUT_STATUS_ID                                           (0x52D) /**< read brownout detect status */
#define DATA_BROWNOUT_STATUS_DLC                                          (8)

#define DATA_UPTIME_MS_ID                                                 (0x52E) /**< read milliseconds since boot */
#define DATA_UPTIME_MS_DLC                                                (8)

#define DATA_WIFI_CHANNEL_ID                                              (0x52F) /**< read WiFi channel number */
#define DATA_WIFI_CHANNEL_DLC                                             (8)

#define DATA_CAN_ERROR_COUNTERS_ID                                        (0x530) /**< read CAN bus error counters */
#define DATA_CAN_ERROR_COUNTERS_DLC                                       (8)

#define DATA_CAN_BUS_STATE_ID                                             (0x531) /**< read CAN bus state */
#define DATA_CAN_BUS_STATE_DLC                                            (8)

#define DATA_FIRMWARE_VERSION_ID                                          (0x532) /**< read firmware build version */
#define DATA_FIRMWARE_VERSION_DLC                                         (8)

#define DATA_FIRMWARE_DATE_ID                                             (0x533) /**< read fimrware build date */
#define DATA_FIRMWARE_DATE_DLC                                            (8)

#define DATA_BOARD_HW_REV_ID                                              (0x534) /**< read board hardware revision */
#define DATA_BOARD_HW_REV_DLC                                             (8)

#define DATA_OTA_PARTITION_INFO_ID                                        (0x535) /**< esp32 OTA partition info */
#define DATA_OTA_PARTITION_INFO_DLC                                       (8)

#define DATA_RESERVED_536_ID                                              (0x536) /**< data reserved 536 */
#define DATA_RESERVED_536_DLC                                             (8)

#define DATA_RESERVED_537_ID                                              (0x537) /**< data reserved 537 */
#define DATA_RESERVED_537_DLC                                             (8)

#define DATA_RESERVED_538_ID                                              (0x538) /**< data reserved 538 */
#define DATA_RESERVED_538_DLC                                             (8)

#define DATA_RESERVED_539_ID                                              (0x539) /**< data reserved 539 */
#define DATA_RESERVED_539_DLC                                             (8)

#define DATA_RESERVED_53A_ID                                              (0x53A) /**< data reserved 53a */
#define DATA_RESERVED_53A_DLC                                             (8)

#define DATA_RESERVED_53B_ID                                              (0x53B) /**< data reserved 53b */
#define DATA_RESERVED_53B_DLC                                             (8)

#define DATA_RESERVED_53C_ID                                              (0x53C) /**< data reserved 53c */
#define DATA_RESERVED_53C_DLC                                             (8)

#define DATA_RESERVED_53D_ID                                              (0x53D) /**< data reserved 53d */
#define DATA_RESERVED_53D_DLC                                             (8)

#define DATA_RESERVED_53E_ID                                              (0x53E) /**< data reserved 53e */
#define DATA_RESERVED_53E_DLC                                             (8)

#define DATA_RESERVED_53F_ID                                              (0x53F) /**< data reserved 53f */
#define DATA_RESERVED_53F_DLC                                             (8)

#define DISP_ANALOG_LED_STRIP_ID                                          (0x700) /**< analog led strip */
#define DISP_ANALOG_LED_STRIP_DLC                                         (8)

#define DISP_ARGB_BUTTON_BACKLIGHT_ID                                     (0x701) /**< argb button backlight */
#define DISP_ARGB_BUTTON_BACKLIGHT_DLC                                    (8)

#define DISP_ARGB_LED_STRIP_ID                                            (0x702) /**< argb led strip */
#define DISP_ARGB_LED_STRIP_DLC                                           (8)

#define DISP_STROBE_MODULE_ID                                             (0x703) /**< strobe module */
#define DISP_STROBE_MODULE_DLC                                            (8)

#define DISP_RESERVED_704_ID                                              (0x704) /**< disp reserved 704 */
#define DISP_RESERVED_704_DLC                                             (8)

#define DISP_OLED_ID                                                      (0x705) /**< non-touch oled display */
#define DISP_OLED_DLC                                                     (8)

#define DISP_RESERVED_706_ID                                              (0x706) /**< disp reserved 706 */
#define DISP_RESERVED_706_DLC                                             (8)

#define DISP_NON_TOUCH_LCD_ID                                             (0x707) /**< non touch lcd */
#define DISP_NON_TOUCH_LCD_DLC                                            (8)

#define DISP_NO_BACKLIGHT_ID                                              (0x708) /**< disp no backlight */
#define DISP_NO_BACKLIGHT_DLC                                             (8)

#define DISP_ARGB_BACKLIGHT_ID                                            (0x709) /**< disp argb backlight */
#define DISP_ARGB_BACKLIGHT_DLC                                           (8)

#define DISP_ANALOG_BACKLIGHT_ID                                          (0x70A) /**< disp analog backlight */
#define DISP_ANALOG_BACKLIGHT_DLC                                         (8)

#define DISP_TOUCHSCREEN_LCD_ID                                           (0x70B) /**< disp touchscreen lcd */
#define DISP_TOUCHSCREEN_LCD_DLC                                          (8)

#define DISP_MONOCHROME_LED_ID                                            (0x70C) /**< monochrome led */
#define DISP_MONOCHROME_LED_DLC                                           (8)

#define DISP_RESERVED_70D_ID                                              (0x70D) /**< disp reserved 70d */
#define DISP_RESERVED_70D_DLC                                             (8)

#define DISP_RESERVED_70E_ID                                              (0x70E) /**< disp reserved 70e */
#define DISP_RESERVED_70E_DLC                                             (8)

#define DISP_RESERVED_70F_ID                                              (0x70F) /**< disp reserved 70f */
#define DISP_RESERVED_70F_DLC                                             (8)

#define INPUT_ANALOG_ADC_ID                                               (0x710) /**< input analog adc */
#define INPUT_ANALOG_ADC_DLC                                              (8)

#define INPUT_DIGITAL_GPIO_ID                                             (0x711) /**< input digital gpio */
#define INPUT_DIGITAL_GPIO_DLC                                            (8)

#define INPUT_RESERVED_712_ID                                             (0x712) /**< input reserved 712 */
#define INPUT_RESERVED_712_DLC                                            (8)

#define INPUT_VIRTUAL_KEYPAD_ID                                           (0x713) /**< input virtual keypad */
#define INPUT_VIRTUAL_KEYPAD_DLC                                          (8)

#define INPUT_ANALOG_KNOB_ID                                              (0x714) /**< analog knob input */
#define INPUT_ANALOG_KNOB_DLC                                             (8)

#define INPUT_JOG_DIAL_CLICK_ID                                           (0x715) /**< jog dial with click */
#define INPUT_JOG_DIAL_CLICK_DLC                                          (8)

#define INPUT_JOG_DIAL_NOCLICK_ID                                         (0x716) /**< jog dial without click */
#define INPUT_JOG_DIAL_NOCLICK_DLC                                        (8)

#define INPUT_MOTION_DET_ID                                               (0x717) /**< motion detector */
#define INPUT_MOTION_DET_DLC                                              (8)

#define INPUT_CAP_TOUCH_ID                                                (0x718) /**< capacitive touch switch stand-alone */
#define INPUT_CAP_TOUCH_DLC                                               (8)

#define INPUT_RESERVED_719_ID                                             (0x719) /**< input reserved 719 */
#define INPUT_RESERVED_719_DLC                                            (8)

#define INPUT_RESERVED_71A_ID                                             (0x71A) /**< input reserved 71a */
#define INPUT_RESERVED_71A_DLC                                            (8)

#define INPUT_RESERVED_71B_ID                                             (0x71B) /**< input reserved 71b */
#define INPUT_RESERVED_71B_DLC                                            (8)

#define INPUT_RESERVED_71C_ID                                             (0x71C) /**< input reserved 71c */
#define INPUT_RESERVED_71C_DLC                                            (8)

#define INPUT_RESERVED_71D_ID                                             (0x71D) /**< input reserved 71d */
#define INPUT_RESERVED_71D_DLC                                            (8)

#define INPUT_RESERVED_71E_ID                                             (0x71E) /**< input reserved 71e */
#define INPUT_RESERVED_71E_DLC                                            (8)

#define INPUT_RESERVED_71F_ID                                             (0x71F) /**< input reserved 71f */
#define INPUT_RESERVED_71F_DLC                                            (8)

#define SENSOR_DIGITAL_TEMP_ID                                            (0x720) /**< sensor digital temp */
#define SENSOR_DIGITAL_TEMP_DLC                                           (8)

#define SENSOR_KTYPE_TEMP_ID                                              (0x721) /**< sensor ktype temp */
#define SENSOR_KTYPE_TEMP_DLC                                             (8)

#define SENSOR_NODE_LASTBOOT_ID                                           (0x722) /**< sensor node last boot timestamp */
#define SENSOR_NODE_LASTBOOT_DLC                                          (8)

#define SENSOR_NODE_PCB_TEMP_ID                                           (0x723) /**< sensor node pcb temp */
#define SENSOR_NODE_PCB_TEMP_DLC                                          (8)

#define SENSOR_NODE_CPU_TEMP_ID                                           (0x724) /**< sensor node cpu temp */
#define SENSOR_NODE_CPU_TEMP_DLC                                          (8)

#define SENSOR_EXT_VOLTAGE_ID                                             (0x725) /**< sensor ext voltage */
#define SENSOR_EXT_VOLTAGE_DLC                                            (8)

#define SENSOR_INT_VOLTAGE_ID                                             (0x726) /**< sensor int voltage */
#define SENSOR_INT_VOLTAGE_DLC                                            (8)

#define SENSOR_INT_CURRENT_ID                                             (0x727) /**< sensor int current */
#define SENSOR_INT_CURRENT_DLC                                            (8)

#define SENSOR_EXT_CURRENT_SHUNT_ID                                       (0x728) /**< sensor ext current shunt */
#define SENSOR_EXT_CURRENT_SHUNT_DLC                                      (8)

#define SENSOR_EXT_CURRENT_HALL_ID                                        (0x729) /**< sensor ext current hall */
#define SENSOR_EXT_CURRENT_HALL_DLC                                       (8)

#define SENSOR_RESERVED_72A_ID                                            (0x72A) /**< sensor reserved 72a */
#define SENSOR_RESERVED_72A_DLC                                           (8)

#define SENSOR_RESERVED_72B_ID                                            (0x72B) /**< sensor reserved 72b */
#define SENSOR_RESERVED_72B_DLC                                           (8)

#define SENSOR_RESERVED_72C_ID                                            (0x72C) /**< sensor reserved 72c */
#define SENSOR_RESERVED_72C_DLC                                           (8)

#define SENSOR_RESERVED_72D_ID                                            (0x72D) /**< sensor reserved 72d */
#define SENSOR_RESERVED_72D_DLC                                           (8)

#define SENSOR_RESERVED_72E_ID                                            (0x72E) /**< sensor reserved 72e */
#define SENSOR_RESERVED_72E_DLC                                           (8)

#define SENSOR_RESERVED_72F_ID                                            (0x72F) /**< sensor reserved 72f */
#define SENSOR_RESERVED_72F_DLC                                           (8)

#define INPUT_AMBIENT_LIGHT_ID                                            (0x730) /**< input ambient light */
#define INPUT_AMBIENT_LIGHT_DLC                                           (8)

#define IMU_X_AXIS_SENSOR_ID                                              (0x731) /**< IMU X Axis sensor */
#define IMU_X_AXIS_SENSOR_DLC                                             (8)

#define IMU_Y_AXIS_SENSOR_ID                                              (0x732) /**< IMU Y Axis sensor */
#define IMU_Y_AXIS_SENSOR_DLC                                             (8)

#define IMU_Z_AXIS_SENSOR_ID                                              (0x733) /**< IMU Z Axis sensor */
#define IMU_Z_AXIS_SENSOR_DLC                                             (8)

#define IMU_X_GYRO_SENSOR_ID                                              (0x734) /**< IMU X Gyro sensor */
#define IMU_X_GYRO_SENSOR_DLC                                             (8)

#define IMU_Y_GYRO_SENSOR_ID                                              (0x735) /**< IMU Y Gyro sensor */
#define IMU_Y_GYRO_SENSOR_DLC                                             (8)

#define IMU_Z_GYRO_SENSOR_ID                                              (0x736) /**< IMU Z Gyro sensor */
#define IMU_Z_GYRO_SENSOR_DLC                                             (8)

#define IMU_TEMP_SENSOR_ID                                                (0x737) /**< IMU temp sensor */
#define IMU_TEMP_SENSOR_DLC                                               (8)

#define GPS_UTC_TIME_ID                                                   (0x738) /**< GPS utc time */
#define GPS_UTC_TIME_DLC                                                  (8)

#define GPS_LATITUDE_ID                                                   (0x739) /**< GPS latitude */
#define GPS_LATITUDE_DLC                                                  (8)

#define GPS_NS_IND_ID                                                     (0x73A) /**< GPS NS IND */
#define GPS_NS_IND_DLC                                                    (8)

#define GPS_LONGITUDE_ID                                                  (0x73B) /**< GPS longitude */
#define GPS_LONGITUDE_DLC                                                 (8)

#define GPS_EW_IND_ID                                                     (0x73C) /**< GPS EW IND */
#define GPS_EW_IND_DLC                                                    (8)

#define GPS_ALTITUDE_ID                                                   (0x73D) /**< GPS altitude */
#define GPS_ALTITUDE_DLC                                                  (8)

#define GPS_STATUS_ID                                                     (0x73E) /**< GPS status */
#define GPS_STATUS_DLC                                                    (8)

#define SENSOR2_RESERVED_73F_ID                                           (0x73F) /**< sensor2 reserved 73f */
#define SENSOR2_RESERVED_73F_DLC                                          (8)

#define OUT_HIGH_CURRENT_SW_ID                                            (0x740) /**< high current solid state switch */
#define OUT_HIGH_CURRENT_SW_DLC                                           (8)

#define OUT_LOW_CURRENT_SW_ID                                             (0x741) /**< low current solid state switch */
#define OUT_LOW_CURRENT_SW_DLC                                            (8)

#define OUT_OPEN_DRAIN_ID                                                 (0x742) /**< open drain output */
#define OUT_OPEN_DRAIN_DLC                                                (8)

#define OUT_MECH_RELAY_ID                                                 (0x743) /**< mechanical relay */
#define OUT_MECH_RELAY_DLC                                                (8)

#define OUT_GPIO_DIGITAL_ID                                               (0x744) /**< gpio digital */
#define OUT_GPIO_DIGITAL_DLC                                              (8)

#define OUT_GPIO_PWM_ID                                                   (0x745) /**< gpio pwm */
#define OUT_GPIO_PWM_DLC                                                  (8)

#define OUT_GPIO_DAC_ID                                                   (0x746) /**< gpio dac */
#define OUT_GPIO_DAC_DLC                                                  (8)

#define OUT_RESERVED_747_ID                                               (0x747) /**< out reserved 747 */
#define OUT_RESERVED_747_DLC                                              (8)

#define OUT_RESERVED_748_ID                                               (0x748) /**< out reserved 748 */
#define OUT_RESERVED_748_DLC                                              (8)

#define OUT_RESERVED_749_ID                                               (0x749) /**< out reserved 749 */
#define OUT_RESERVED_749_DLC                                              (8)

#define OUT_RESERVED_74A_ID                                               (0x74A) /**< out reserved 74a */
#define OUT_RESERVED_74A_DLC                                              (8)

#define OUT_RESERVED_74B_ID                                               (0x74B) /**< out reserved 74b */
#define OUT_RESERVED_74B_DLC                                              (8)

#define OUT_RESERVED_74C_ID                                               (0x74C) /**< out reserved 74c */
#define OUT_RESERVED_74C_DLC                                              (8)

#define OUT_RESERVED_74D_ID                                               (0x74D) /**< out reserved 74d */
#define OUT_RESERVED_74D_DLC                                              (8)

#define OUT_RESERVED_74E_ID                                               (0x74E) /**< out reserved 74e */
#define OUT_RESERVED_74E_DLC                                              (8)

#define OUT_RESERVED_74F_ID                                               (0x74F) /**< out reserved 74f */
#define OUT_RESERVED_74F_DLC                                              (8)

#define INTRO_RESERVED_750_ID                                             (0x750) /**< intro reserved 750 */
#define INTRO_RESERVED_750_DLC                                            (8)

#define INTRO_RESERVED_751_ID                                             (0x751) /**< intro reserved 751 */
#define INTRO_RESERVED_751_DLC                                            (8)

#define INTRO_RESERVED_752_ID                                             (0x752) /**< intro reserved 752 */
#define INTRO_RESERVED_752_DLC                                            (8)

#define INTRO_RESERVED_753_ID                                             (0x753) /**< intro reserved 753 */
#define INTRO_RESERVED_753_DLC                                            (8)

#define INTRO_RESERVED_754_ID                                             (0x754) /**< intro reserved 754 */
#define INTRO_RESERVED_754_DLC                                            (8)

#define INTRO_RESERVED_755_ID                                             (0x755) /**< intro reserved 755 */
#define INTRO_RESERVED_755_DLC                                            (8)

#define INTRO_RESERVED_756_ID                                             (0x756) /**< intro reserved 756 */
#define INTRO_RESERVED_756_DLC                                            (8)

#define INTRO_RESERVED_757_ID                                             (0x757) /**< intro reserved 757 */
#define INTRO_RESERVED_757_DLC                                            (8)

#define INTRO_RESERVED_758_ID                                             (0x758) /**< intro reserved 758 */
#define INTRO_RESERVED_758_DLC                                            (8)

#define INTRO_RESERVED_759_ID                                             (0x759) /**< intro reserved 759 */
#define INTRO_RESERVED_759_DLC                                            (8)

#define INTRO_RESERVED_75A_ID                                             (0x75A) /**< intro reserved 75a */
#define INTRO_RESERVED_75A_DLC                                            (8)

#define INTRO_RESERVED_75B_ID                                             (0x75B) /**< intro reserved 75b */
#define INTRO_RESERVED_75B_DLC                                            (8)

#define INTRO_RESERVED_75C_ID                                             (0x75C) /**< intro reserved 75c */
#define INTRO_RESERVED_75C_DLC                                            (8)

#define INTRO_RESERVED_75D_ID                                             (0x75D) /**< intro reserved 75d */
#define INTRO_RESERVED_75D_DLC                                            (8)

#define INTRO_RESERVED_75E_ID                                             (0x75E) /**< intro reserved 75e */
#define INTRO_RESERVED_75E_DLC                                            (8)

#define INTRO_RESERVED_75F_ID                                             (0x75F) /**< intro reserved 75f */
#define INTRO_RESERVED_75F_DLC                                            (8)

#define SENSOR_WIFI_RSSI_ID                                               (0x760) /**< wifi rssi for nodes that support it */
#define SENSOR_WIFI_RSSI_DLC                                              (8)

#define SENSOR_RTOS_FREE_HEAP_ID                                          (0x761) /**< freertos free heap memory */
#define SENSOR_RTOS_FREE_HEAP_DLC                                         (8)

#define SENSOR_RTOS_HIGH_WATER_ID                                         (0x762) /**< freertos high water mark */
#define SENSOR_RTOS_HIGH_WATER_DLC                                        (8)

#define SENSOR_RESET_REASON_ID                                            (0x763) /**< read last reset reason */
#define SENSOR_RESET_REASON_DLC                                           (8)

#define SENSOR_BROWNOUT_STATUS_ID                                         (0x764) /**< read brownout detect status */
#define SENSOR_BROWNOUT_STATUS_DLC                                        (8)

#define SENSOR_UPTIME_MS_ID                                               (0x765) /**< read milliseconds since boot */
#define SENSOR_UPTIME_MS_DLC                                              (8)

#define SENSOR_WIFI_CHANNEL_ID                                            (0x766) /**< read WiFi channel number */
#define SENSOR_WIFI_CHANNEL_DLC                                           (8)

#define SENSOR_CAN_ERR_COUNT_ID                                           (0x767) /**< read CAN bus error counters */
#define SENSOR_CAN_ERR_COUNT_DLC                                          (8)

#define SENSOR_CAN_BUS_STATE_ID                                           (0x768) /**< read CAN bus state */
#define SENSOR_CAN_BUS_STATE_DLC                                          (8)

#define SENSOR_FIRMWARE_VER_ID                                            (0x769) /**< read firmware build version */
#define SENSOR_FIRMWARE_VER_DLC                                           (8)

#define SENSOR_FIRMWARE_DATE_ID                                           (0x76A) /**< read fimrware build date */
#define SENSOR_FIRMWARE_DATE_DLC                                          (8)

#define SENSOR_BOARD_HW_REV_ID                                            (0x76B) /**< read board hardware revision */
#define SENSOR_BOARD_HW_REV_DLC                                           (8)

#define SENSOR_OTA_PART_INFO_ID                                           (0x76C) /**< esp32 OTA partition info */
#define SENSOR_OTA_PART_INFO_DLC                                          (8)

#define SYS_RESERVED_76D_ID                                               (0x76D) /**< sys reserved 76d */
#define SYS_RESERVED_76D_DLC                                              (8)

#define SYS_RESERVED_76E_ID                                               (0x76E) /**< sys reserved 76e */
#define SYS_RESERVED_76E_DLC                                              (8)

#define SYS_RESERVED_76F_ID                                               (0x76F) /**< sys reserved 76f */
#define SYS_RESERVED_76F_DLC                                              (8)

#define SYS_RESERVED_770_ID                                               (0x770) /**< sys reserved 770 */
#define SYS_RESERVED_770_DLC                                              (8)

#define SYS_RESERVED_771_ID                                               (0x771) /**< sys reserved 771 */
#define SYS_RESERVED_771_DLC                                              (8)

#define SYS_RESERVED_772_ID                                               (0x772) /**< sys reserved 772 */
#define SYS_RESERVED_772_DLC                                              (8)

#define SYS_RESERVED_773_ID                                               (0x773) /**< sys reserved 773 */
#define SYS_RESERVED_773_DLC                                              (8)

#define SYS_RESERVED_774_ID                                               (0x774) /**< sys reserved 774 */
#define SYS_RESERVED_774_DLC                                              (8)

#define SYS_RESERVED_775_ID                                               (0x775) /**< sys reserved 775 */
#define SYS_RESERVED_775_DLC                                              (8)

#define SYS_RESERVED_776_ID                                               (0x776) /**< sys reserved 776 */
#define SYS_RESERVED_776_DLC                                              (8)

#define SYS_RESERVED_777_ID                                               (0x777) /**< sys reserved 777 */
#define SYS_RESERVED_777_DLC                                              (8)

#define SYS_RESERVED_778_ID                                               (0x778) /**< sys reserved 778 */
#define SYS_RESERVED_778_DLC                                              (8)

#define SYS_RESERVED_779_ID                                               (0x779) /**< sys reserved 779 */
#define SYS_RESERVED_779_DLC                                              (8)

#define SYS_RESERVED_77A_ID                                               (0x77A) /**< sys reserved 77a */
#define SYS_RESERVED_77A_DLC                                              (8)

#define SYS_RESERVED_77B_ID                                               (0x77B) /**< sys reserved 77b */
#define SYS_RESERVED_77B_DLC                                              (8)

#define SYS_RESERVED_77C_ID                                               (0x77C) /**< sys reserved 77c */
#define SYS_RESERVED_77C_DLC                                              (8)

#define SYS_RESERVED_77D_ID                                               (0x77D) /**< sys reserved 77d */
#define SYS_RESERVED_77D_DLC                                              (8)

#define SYS_RESERVED_77E_ID                                               (0x77E) /**< sys reserved 77e */
#define SYS_RESERVED_77E_DLC                                              (8)

#define SYS_RESERVED_77F_ID                                               (0x77F) /**< sys reserved 77f */
#define SYS_RESERVED_77F_DLC                                              (8)

#define BOX_SW_3GANG_ID                                                   (0x780) /**< 3 gang switch box, 2 high, 1 low */
#define BOX_SW_3GANG_DLC                                                  (8)

#define BOX_SW_4GANG_ID                                                   (0x781) /**< 4-gang switch box, 2 high, 2 low */
#define BOX_SW_4GANG_DLC                                                  (8)

#define BOX_SW_6GANG_HIGH_ID                                              (0x782) /**< 6-gang switch box, 4 high, 2 low */
#define BOX_SW_6GANG_HIGH_DLC                                             (8)

#define BOX_SW_6GANG_LOW_ID                                               (0x783) /**< 6-gang switch box, 2 high, 4 low */
#define BOX_SW_6GANG_LOW_DLC                                              (8)

#define BOX_SW_2GANG_HIGH_ID                                              (0x784) /**< 2-gang switch box, 2 high */
#define BOX_SW_2GANG_HIGH_DLC                                             (8)

#define BOX_SW_2GANG_LOW_ID                                               (0x785) /**< 2-gang switch box, 2 low */
#define BOX_SW_2GANG_LOW_DLC                                              (8)

#define BOX_MULTI_4XTEMP_ID                                               (0x786) /**< 4-digital multi temp input box */
#define BOX_MULTI_4XTEMP_DLC                                              (8)

#define BOX_SW_4RELAY_ID                                                  (0x787) /**< 4-gang relay output box */
#define BOX_SW_4RELAY_DLC                                                 (8)

#define BOX_MULTI_TVA_ID                                                  (0x788) /**< temp, volt, current input box */
#define BOX_MULTI_TVA_DLC                                                 (8)

#define BOX_SW_8RELAY_ID                                                  (0x789) /**< 8-gang relay output box */
#define BOX_SW_8RELAY_DLC                                                 (8)

#define BOX_MULTI_4X4IO_ID                                                (0x78A) /**< input - output box, 4 in, 4 out */
#define BOX_MULTI_4X4IO_DLC                                               (8)

#define BOX_MULTI_IO_ID                                                   (0x78B) /**< input - output box, multiple options */
#define BOX_MULTI_IO_DLC                                                  (8)

#define BOX_RESERVED_78C_ID                                               (0x78C) /**< box reserved 78c */
#define BOX_RESERVED_78C_DLC                                              (8)

#define BOX_RESERVED_78D_ID                                               (0x78D) /**< box reserved 78d */
#define BOX_RESERVED_78D_DLC                                              (8)

#define BOX_RESERVED_78E_ID                                               (0x78E) /**< box reserved 78e */
#define BOX_RESERVED_78E_DLC                                              (8)

#define BOX_RESERVED_78F_ID                                               (0x78F) /**< box reserved 78f */
#define BOX_RESERVED_78F_DLC                                              (8)

#define IFACE_8X4_ARGB_KEYPAD_ID                                          (0x790) /**< 8x4 argb keypad */
#define IFACE_8X4_ARGB_KEYPAD_DLC                                         (8)

#define IFACE_4X4_ARGB_KEYPAD_ID                                          (0x791) /**< 4x4 argb keypad */
#define IFACE_4X4_ARGB_KEYPAD_DLC                                         (8)

#define IFACE_TOUCHSCREEN_TYPE_A_ID                                       (0x792) /**< touchscreen type a */
#define IFACE_TOUCHSCREEN_TYPE_A_DLC                                      (8)

#define IFACE_TOUCHSCREEN_TYPE_B_ID                                       (0x793) /**< touchscreen type b */
#define IFACE_TOUCHSCREEN_TYPE_B_DLC                                      (8)

#define IFACE_NEXTION_TYPE_A_ID                                           (0x794) /**< nextion type a */
#define IFACE_NEXTION_TYPE_A_DLC                                          (8)

#define IFACE_NEXTION_TYPE_B_ID                                           (0x795) /**< nextion type b */
#define IFACE_NEXTION_TYPE_B_DLC                                          (8)

#define IFACE_RESERVED_796_ID                                             (0x796) /**< iface reserved 796 */
#define IFACE_RESERVED_796_DLC                                            (8)

#define IFACE_RESERVED_797_ID                                             (0x797) /**< iface reserved 797 */
#define IFACE_RESERVED_797_DLC                                            (8)

#define IFACE_RESERVED_798_ID                                             (0x798) /**< iface reserved 798 */
#define IFACE_RESERVED_798_DLC                                            (8)

#define IFACE_6_AXIS_IMU_ID                                               (0x799) /**< 6 axis imu */
#define IFACE_6_AXIS_IMU_DLC                                              (8)

#define IFACE_3X5_BUTTON_BOX_ID                                           (0x79A) /**< 3x5 button box */
#define IFACE_3X5_BUTTON_BOX_DLC                                          (8)

#define IFACE_4X6_BUTTON_BOX_ID                                           (0x79B) /**< 4x6 button box */
#define IFACE_4X6_BUTTON_BOX_DLC                                          (8)

#define IFACE_ARGB_MULTI_ID                                               (0x79C) /**< iface ARGB multi */
#define IFACE_ARGB_MULTI_DLC                                              (8)

#define IFACE_RESERVED_79D_ID                                             (0x79D) /**< iface reserved 79d */
#define IFACE_RESERVED_79D_DLC                                            (8)

#define IFACE_RESERVED_79E_ID                                             (0x79E) /**< iface reserved 79e */
#define IFACE_RESERVED_79E_DLC                                            (8)

#define IFACE_RESERVED_79F_ID                                             (0x79F) /**< iface reserved 79f */
#define IFACE_RESERVED_79F_DLC                                            (8)

#endif /* CANBUS_MSG_H_ */